/* GENERATED by scripts/build-messengerbot-v4.mjs. Edit SHARED or KLOL_KAKAO_BOT_V4_FEATURES.js. */
/* eslint-disable */
/* Shared ES5 transport. It intentionally contains no response() callback. */
var KLOL_V4 = (function () {
  var CONTRACT = "KLOL_KAKAO_COMMAND_V4";
  var ENDPOINT = "/api/integrations/kakao/v4/commands";
  var BASE_URL_KEY = "KLOL_V2_BASE_URL";
  var SIGNING_SECRET_KEY = "KLOL_V2_KAKAO_WEBHOOK_SECRET_CURRENT";
  var SIGNING_KEY_ID_KEY = "KLOL_V2_KAKAO_WEBHOOK_KEY_ID_CURRENT";
  var IDENTITY_SECRET_KEY = "KLOL_V2_KAKAO_IDENTITY_SECRET";
  var BOOT_ID = String(java.util.UUID.randomUUID().toString()).replace(/-/g, "").substring(0, 16);
  var eventCounter = 0;

  function trimText(value) {
    return String(value == null ? "" : value).replace(/^\s+|\s+$/g, "");
  }

  function setting(key) {
    try {
      return trimText(String(DataBase.getDataBase(key) || ""));
    } catch (ignored) {
      return "";
    }
  }

  function utf8(value) {
    return new java.lang.String(String(value)).getBytes(java.nio.charset.StandardCharsets.UTF_8);
  }

  function hex(bytes) {
    var builder = new java.lang.StringBuilder(bytes.length * 2);
    var index = 0;
    var value = 0;
    for (index = 0; index < bytes.length; index += 1) {
      value = bytes[index] & 255;
      if (value < 16) builder.append("0");
      builder.append(java.lang.Integer.toHexString(value));
    }
    return String(builder.toString());
  }

  function sha256(value) {
    return hex(java.security.MessageDigest.getInstance("SHA-256").digest(utf8(value)));
  }

  function hmac(secret, value) {
    var mac = javax.crypto.Mac.getInstance("HmacSHA256");
    mac.init(new javax.crypto.spec.SecretKeySpec(utf8(secret), "HmacSHA256"));
    return hex(mac.doFinal(utf8(value)));
  }

  function requiredSecret(key, label) {
    var value = setting(key);
    if (utf8(value).length < 32) throw new Error(label + " 비공개 설정을 확인해 주세요.");
    return value;
  }

  function profile(value) {
    if (value !== "RECRUIT" && value !== "FEATURES") throw new Error("V4 profileId를 확인해 주세요.");
    return value;
  }

  function baseUrl() {
    var value = setting(BASE_URL_KEY).replace(/\/+$/, "");
    if (!/^https:\/\/[A-Za-z0-9](?:[A-Za-z0-9.-]{0,251}[A-Za-z0-9])?(?::443)?$/.test(value)) {
      throw new Error("V4 HTTPS 주소 설정을 확인해 주세요.");
    }
    return value;
  }

  function installationId(profileId) {
    return "install-" + hmac(requiredSecret(IDENTITY_SECRET_KEY, "익명 식별 키"), "installation-id\nKLOL_V4\n" + profile(profileId)).substring(0, 32);
  }

  function senderId(sender, userHash) {
    var stable = trimText(userHash);
    var prefix = stable ? "sender-user-" : "sender-display-";
    if (!stable) stable = trimText(sender);
    return prefix + hmac(requiredSecret(IDENTITY_SECRET_KEY, "익명 식별 키"), "sender-id\n" + stable).substring(0, 32);
  }

  function nextEventId(profileId, logId) {
    var stableLogId = trimText(logId);
    if (stableLogId) return "event-log-" + sha256(profile(profileId) + "\n" + stableLogId).substring(0, 32);
    eventCounter += 1;
    return "event-boot-" + BOOT_ID + "-" + String(eventCounter);
  }

  function canonicalLocalCommand(value) {
    var text = trimText(value);
    var stripped = "";
    if (!text || text === "/" || text.indexOf("//") === 0) return null;
    if (text.charAt(0) !== "/") return text;
    stripped = text.substring(1);
    return !stripped || /^\s/.test(stripped) ? null : stripped;
  }

  function localReply(profileId, text, codeVersion) {
    var command = canonicalLocalCommand(text);
    if (command === "봇버전") {
      return "[K-LOL.GG V4 봇 버전]\n프로필: " + profile(profileId) + "\n버전: " + codeVersion + "\n설치본: " + installationId(profileId);
    }
    if (command === "도움말" || command === "명령어") {
      if (profileId === "RECRUIT") return "[K-LOL.GG 구인 도움말]\n\n1. 파티\n생성: 5인파티\n현황: 구인현황\n종료: 번호ㅉ\n\n2. 내전\n생성: 내전구인\n현황: 내전현황\n매일 오전 6시 자동 종료\n\n3. 스크림\n생성: 스크림구인\n현황: 스크림현황\n매일 오전 6시 자동 종료\n\n공통: 양식 복사 → 이름 추가·삭제 → 양식 전체 전송";
      return "[K-LOL.GG V4 도움말]\n서버 상태: V4상태\n계약 확인: V4계약확인\n봇 정보: 봇버전\n일반 기능 명령은 서버 라우터 연결 후 제공됩니다.";
    }
    return null;
  }

  function shouldIgnore(profileId, text, sender) {
    var normalized = String(text == null ? "" : text);
    var configuredName = setting("KLOL_V4_BOT_SELF_NAME_" + profile(profileId));
    if (!normalized || normalized.length > 20000) return true;
    if (trimText(sender) === "오픈채팅봇") return true;
    return Boolean(configuredName && trimText(sender) === configuredName);
  }

  function parseJson(value) {
    try {
      return JSON.parse(String(value || ""));
    } catch (ignored) {
      return null;
    }
  }

  function send(profileId, text, sender, logId, userHash) {
    var timestamp = Math.floor(new Date().getTime() / 1000);
    var nonce = String(java.util.UUID.randomUUID().toString()).replace(/-/g, "");
    var keyId = setting(SIGNING_KEY_ID_KEY) || "current";
    var eventId = nextEventId(profileId, logId);
    var body = JSON.stringify({
      profileId: profile(profileId),
      installationId: installationId(profileId),
      senderId: senderId(sender, userHash),
      eventId: eventId,
      timestamp: timestamp,
      nonce: nonce,
      text: String(text)
    });
    var material = CONTRACT + "\n" + keyId + "\n" + sha256(body);
    var response = org.jsoup.Jsoup.connect(baseUrl() + ENDPOINT)
      .ignoreContentType(true)
      .ignoreHttpErrors(true)
      .method(org.jsoup.Connection.Method.POST)
      .header("Content-Type", "application/json; charset=utf-8")
      .header("Accept", "application/json")
      .header("x-klol-key-id", keyId)
      .header("x-klol-signature", "v4=" + hmac(requiredSecret(SIGNING_SECRET_KEY, "서명 키"), material))
      .header("Idempotency-Key", eventId)
      .timeout(5000)
      .requestBody(body)
      .execute();
    return {
      ok: response.statusCode() >= 200 && response.statusCode() < 300,
      status: response.statusCode(),
      body: parseJson(response.body()),
      traceId: trimText(response.header("X-Trace-Id"))
    };
  }

  function resultReply(result) {
    if (result && result.ok && result.body && typeof result.body.reply === "string") return result.body.reply;
    if (result && result.ok) return "";
    var detail = result && result.body && typeof result.body.detail === "string" ? result.body.detail : "잠시 후 다시 시도해 주세요.";
    return "[K-LOL.GG 요청 실패]\n" + detail + (result && result.traceId ? "\n문의 코드: " + result.traceId : "");
  }

  return {
    localReply: localReply,
    resultReply: resultReply,
    send: send,
    shouldIgnore: shouldIgnore
  };
}());

/* eslint-disable */
var KLOL_V4_PROFILE_ID = "FEATURES";
var KLOL_V4_BOT_CODE_VERSION = "KLOL_KAKAO_BOT_V4_FEATURES_2026_09_10_R1";

function response(room, msg, sender, isGroupChat, replier, imageDB, packageName, isMention, logId, channelId, userHash) {
  var text = String(msg == null ? "" : msg);
  var local = null;
  var result = null;
  var reply = "";
  if (KLOL_V4.shouldIgnore(KLOL_V4_PROFILE_ID, text, sender)) return;
  local = KLOL_V4.localReply(KLOL_V4_PROFILE_ID, text, KLOL_V4_BOT_CODE_VERSION);
  if (local) {
    replier.reply(local);
    return;
  }
  try {
    result = KLOL_V4.send(KLOL_V4_PROFILE_ID, text, sender, logId, userHash);
    reply = KLOL_V4.resultReply(result);
    if (reply) replier.reply(reply);
  } catch (error) {
    replier.reply("[K-LOL.GG 요청 실패]\n" + String(error && error.message ? error.message : error));
  }
}
