import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { resolve } from "node:path";
import test from "node:test";

import { analyzeRhinoStatic } from "../scripts/lib/messengerbot-rhino-static.mjs";

const root = resolve(import.meta.dirname, "..");
const require = createRequire(import.meta.url);
const acorn = require("next/dist/compiled/acorn");
const profiles = ["RECRUIT", "FEATURES"];

async function artifact(profile) {
  const path = resolve(root, `integrations/messengerbot-r/v4/KLOL_KAKAO_BOT_V4_${profile}_MESSENGERBOT_R.js`);
  return { path, source: await readFile(path, "utf8") };
}

function responseBody(program) {
  const declaration = program.body.find((node) => node.type === "FunctionDeclaration" && node.id?.name === "response");
  assert.ok(declaration, "response() declaration must exist");
  return declaration.body;
}

test("[A01] both phone artifacts are readable ES5 single files below 40,000 characters", async () => {
  for (const profile of profiles) {
    const { source } = await artifact(profile);
    const normalized = source.replace(/\r\n?/gu, "\n");
    const lines = normalized.split("\n");
    const program = acorn.parse(normalized, { ecmaVersion: 5, allowReserved: true, preserveParens: true });
    assert.ok(normalized.length <= 40_000, `${profile}: ${normalized.length} characters`);
    assert.ok(lines.length >= 150, `${profile}: ${lines.length} physical lines are not reviewable enough`);
    assert.ok(Math.max(...lines.map((line) => line.length)) <= 1_000, `${profile}: an unreadably long generated line exists`);
    assert.ok(program.body.filter((node) => node.type === "FunctionDeclaration").length >= 1);
    assert.equal((normalized.match(/function\s+response\s*\(/gu) ?? []).length, 1);
    assert.match(normalized, /GENERATED by scripts\/build-messengerbot-v4\.mjs/u);
  }
});

test("[A02] both final artifacts have zero Rhino static warning candidates", async () => {
  for (const profile of profiles) {
    const { source } = await artifact(profile);
    const program = acorn.parse(source, { ecmaVersion: 5, allowReserved: true, preserveParens: true });
    const findings = analyzeRhinoStatic(program);
    assert.deepEqual({
      statementCandidates: findings.statementCandidates.length,
      unsafeSequenceOperands: findings.unsafeSequenceOperands.length,
      voidExpressions: findings.voidExpressions.length,
      bareAssignmentConditions: findings.bareAssignmentConditions.length,
    }, {
      statementCandidates: 0,
      unsafeSequenceOperands: 0,
      voidExpressions: 0,
      bareAssignmentConditions: 0,
    }, profile);
  }
});

test("[A03] generated artifacts fix one static profile ID each", async () => {
  for (const profile of profiles) {
    const { source } = await artifact(profile);
    assert.equal((source.match(/var\s+KLOL_V4_PROFILE_ID\s*=\s*"(?:RECRUIT|FEATURES)"/gu) ?? []).length, 1);
    assert.match(source, new RegExp(`var\\s+KLOL_V4_PROFILE_ID\\s*=\\s*"${profile}"`, "u"));
    assert.doesNotMatch(source, new RegExp(`KLOL_V4_PROFILE_ID\\s*=\\s*"${profile === "RECRUIT" ? "FEATURES" : "RECRUIT"}"`, "u"));
  }
});

test("[A04] callback room, channel and group values are neither read nor transmitted", async () => {
  for (const profile of profiles) {
    const { source } = await artifact(profile);
    const program = acorn.parse(source, { ecmaVersion: 5, allowReserved: true, preserveParens: true });
    const body = responseBody(program);
    const bodySource = source.slice(body.start + 1, body.end - 1);
    assert.doesNotMatch(bodySource, /\b(?:room|roomName|channelId|isGroupChat)\b/u, `${profile}: callback identity read`);
    assert.doesNotMatch(source, /x-klol-(?:room|channel|room-name)|"roomName"|"channelId"/iu, `${profile}: forbidden identity transmission`);
  }
});

test("[A05] text transport timeout is no more than five seconds", async () => {
  const shared = await readFile(resolve(root, "integrations/messengerbot-r/v4/KLOL_KAKAO_BOT_V4_SHARED.js"), "utf8");
  const timeout = /\.timeout\((\d+)\)/u.exec(shared);
  assert.ok(timeout, "text transport timeout must be explicit");
  assert.ok(Number(timeout[1]) <= 5_000, `timeout=${timeout[1]}ms`);
});
