import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import test from "node:test";

const root = resolve(import.meta.dirname, "..");
const read = (path) => readFile(resolve(root, path), "utf8");

test("paste-ready V41 bot routes major commands only through the signed V2 transport", async () => {
  const [transport, router, complete, build] = await Promise.all([
    read("integrations/messengerbot-r/KLOL_KAKAO_BOT_V41_V2_TRANSPORT.js"),
    read("integrations/messengerbot-r/KLOL_KAKAO_BOT_V41_V2_ROUTER.js"),
    read("integrations/messengerbot-r/KLOL_KAKAO_BOT_V41_V2_COMPLETE.js"),
    read("scripts/build-messengerbot-v41.mjs"),
  ]);
  for (const endpoint of [
    "/api/integrations/kakao/recruits",
    "/api/integrations/kakao/search-player",
    "/api/integrations/kakao/openchat",
    "/api/integrations/kakao/season-applications",
    "/api/integrations/kakao/operation-forms",
    "/api/integrations/kakao/image-receive",
  ]) assert.match(transport, new RegExp(endpoint.replaceAll("/", "\\/")));
  for (const evidence of [
    "KLOL_KAKAO_WEBHOOK_V1", "HmacSHA256", "x-klol-timestamp", "x-klol-nonce",
    "x-klol-room", "x-klol-sender", "x-klol-bot-self", "x-klol-signature",
    "Idempotency-Key",
  ]) assert.match(transport, new RegExp(evidence));
  assert.match(transport, /requestBody\(rawBody\)/u);
  assert.doesNotMatch(transport, /KLOL_KAKAO_(?:RECRUIT|OPENCHAT|SEARCH_PLAYER)_SECRET/u);
  assert.doesNotMatch(transport, /party-recruits|destruction-scrim-recruits/u);
  assert.doesNotMatch(transport, /function\s+response\s*\(/u);
  assert.match(transport, /KLOL_V2_KAKAO_IDENTITY_SECRET/u);
  assert.match(transport, /identityForChat/u);

  assert.match(router, /function\s+response\s*\(/u);
  for (const call of ["searchPlayer", "openchatStatus", "seasonApplications", "recruit", "operationForm", "imageReceive"]) {
    assert.match(router, new RegExp(`KLOL_V2_KAKAO\\.${call}`));
  }
  assert.match(router, /\/V2연동확인/u);
  assert.match(router, /v41SaveRecruitState/u);
  assert.match(router, /KLOL_V2_KAKAO\.newUuid/u);
  assert.match(router, /구형 문장형 등록은 종료/u);
  assert.equal(complete, `/* GENERATED by scripts/build-messengerbot-v41.mjs. Edit TRANSPORT or ROUTER, then rebuild. */\n${transport.trim()}\n\n${router.trim()}\n`);
  assert.match(build, /writeFile\(outputPath/u);
});

test("Kakao pending slot lookup is lifecycle-neutral and only cancels ACTIVE rows", async () => {
  const source = await read("src/modules/recruiting/kakao-assistant/postgres-kakao-assistant.ts");
  const start = source.indexOf("const currentPending =");
  const end = source.indexOf("for (const { participant, candidates }", start);
  assert.ok(start > 0 && end > start);
  const reconciliation = source.slice(start, end);
  assert.doesNotMatch(reconciliation, /eq\(seasonKakaoPendingApplications\.status,\s*"ACTIVE"\)/u);
  assert.match(reconciliation, /pending\.status !== "ACTIVE"/u);
  assert.match(source, /planSeasonApplicationMerge\(current \?\? null\)/u);
  assert.match(source, /existingPending\?\.status === "ACTIVE"/u);
  assert.match(source, /status: "ACTIVE" as const[\s\S]*cancelledAt: null,[\s\S]*resolvedAt: null/u);
});
