import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import test from "node:test";
import vm from "node:vm";

const root = resolve(import.meta.dirname, "..");
const read = (path) => readFile(resolve(root, path), "utf8");

test("paste-ready V41 bot routes major commands only through the signed V2 transport", async () => {
  const [transport, compatibility, router, complete, mobile, build] = await Promise.all([
    read("integrations/messengerbot-r/KLOL_KAKAO_BOT_V41_V2_TRANSPORT.js"),
    read("integrations/messengerbot-r/KLOL_KAKAO_BOT_V41_V1_COMPAT.js"),
    read("integrations/messengerbot-r/KLOL_KAKAO_BOT_V41_V2_ROUTER.js"),
    read("integrations/messengerbot-r/KLOL_KAKAO_BOT_V41_V2_COMPLETE.js"),
    read("integrations/messengerbot-r/KLOL_KAKAO_BOT_V41_MESSENGERBOT_R.js"),
    read("scripts/build-messengerbot-v41.mjs"),
  ]);
  for (const endpoint of [
    "/api/integrations/kakao/recruits",
    "/api/integrations/kakao/search-player",
    "/api/integrations/kakao/openchat",
    "/api/integrations/kakao/season-applications",
    "/api/integrations/kakao/operation-forms",
    "/api/integrations/kakao/image-receive",
    "/api/integrations/kakao/scheduled-notice",
    "/api/integrations/kakao/pair-room",
  ]) assert.match(transport, new RegExp(endpoint.replaceAll("/", "\\/")));
  for (const evidence of [
    "KLOL_KAKAO_WEBHOOK_V3", "HmacSHA256", "x-klol-timestamp", "x-klol-nonce",
    "x-klol-installation", "x-klol-key-id", "x-klol-delivery", "x-klol-bot-version",
    "x-klol-room", "x-klol-sender", "x-klol-bot-self", "x-klol-signature",
    "Idempotency-Key",
  ]) assert.match(transport, new RegExp(evidence));
  assert.match(transport, /function\s+publicBaseUrl\s*\(/u);
  assert.match(transport, /KLOL_V2_BASE_URL 비공개 설정/u);
  assert.doesNotMatch(`${transport}\n${router}`, /https:\/\/k-lol-gg\.vercel\.app/u);
  assert.match(transport, /requestBody\(rawBody\)/u);
  assert.doesNotMatch(transport, /KLOL_KAKAO_(?:RECRUIT|OPENCHAT|SEARCH_PLAYER)_SECRET/u);
  assert.doesNotMatch(transport, /party-recruits|destruction-scrim-recruits/u);
  assert.doesNotMatch(transport, /function\s+response\s*\(/u);
  assert.equal((`${transport}\n${compatibility}\n${router}`.match(/function\s+response\s*\(/gu) ?? []).length, 1, "the paste-ready sources must define exactly one callback entry point");
  assert.doesNotMatch(`${transport}\n${compatibility}\n${router}`, /BotManager|addListener|setCommandPrefix/u);
  assert.match(transport, /KLOL_V2_KAKAO_IDENTITY_SECRET/u);
  assert.match(transport, /identityForChat/u);
  assert.match(transport, /signature\s*=\s*"v3="/u);
  assert.match(transport, /signatureMaterial\(timestampSeconds, nonce, installId, keyId, deliveryId, version, roomId, senderId, bodyDigestHex\)/u);
  assert.match(transport, /body\.source = context\.commandSource === "RAW_V2" \? "RAW_V2" : "COMPAT_V1"/u);
  assert.match(router, /commandSource: "RAW_V2"/u);

  assert.match(router, /function\s+response\s*\(/u);
  for (const call of ["playerRecord", "recentMatches", "ranking", "openchatStatus", "seasonApplications", "recruit", "operationForm", "imageReceive", "scheduledNotice"]) {
    assert.match(router, new RegExp(`KLOL_V2_KAKAO\\.${call}`));
  }
  assert.match(router, /\/V2연동확인/u);
  assert.match(router, /v41SaveRecruitState/u);
  assert.match(router, /KLOL_V2_KAKAO\.deterministicMessageUuid/u);
  assert.match(router, /v41HandleCompat/u);
  assert.match(compatibility, /parsePartyCreateCommand/u);
  assert.match(compatibility, /parseOperationForm/u);
  assert.match(router, /아직 사이트에 반영하지 않았습니다/u);
  assert.match(router, /v41ConfirmSeasonPreview/u);
  assert.match(router, /v41IsBotEcho/u);
  assert.match(router, /v41ClearImageSession/u);
  for (const label of ["플레이어:", "신청일:", "회차:", "주라인:", "부라인:", "상태:", "출처:"]) {
    assert.match(router, new RegExp(label));
  }
  assert.match(router, /entry\.player \? entry\.player\.displayName : entry\.suppliedName/u);
  const bundleMarker = "KLOL_V41_BUNDLE_R14_INSTALLATION_DEDUPE";
  const lf = (source) => source.replace(/\r\n?/gu, "\n");
  assert.equal(lf(complete), `/* GENERATED by scripts/build-messengerbot-v41.mjs. Edit TRANSPORT, V1_COMPAT, or ROUTER, then rebuild. */\nvar KLOL_V41_BUNDLE_START_SENTINEL = "${bundleMarker}_START";\n${lf(transport).trim()}\n\n${lf(compatibility).trim()}\n\n${lf(router).trim()}\nvar KLOL_V41_BUNDLE_END_SENTINEL = "${bundleMarker}_END";\n`);
  assert.match(build, /writeFile\(outputPath/u);
  assert.match(build, /writeFile\(mobileOutputPath/u);
  assert.match(mobile, /(?:function\s+response\s*\(|response\s*=\s*function\s*\()/u);
  assert.match(mobile, /KLOL_KAKAO_BOT_V41_V3_2026_09_09_R14_INSTALLATION_DEDUPE/u);
  assert.match(complete, /KLOL_V41_BUNDLE_R14_INSTALLATION_DEDUPE_START/u);
  assert.match(complete, /KLOL_V41_BUNDLE_R14_INSTALLATION_DEDUPE_END/u);
  assert.ok(mobile.length < complete.length, "mobile bundle should be smaller than the readable source bundle");
  assert.ok(mobile.length < 65_535, "mobile bundle must stay below MessengerBot R's character limit");
  assert.ok(mobile.length + (mobile.match(/\n/gu) ?? []).length < 65_535, "mobile bundle must stay below the character limit after CRLF conversion");
  assert.match(build, /projectedCrLfLength/u);
  assert.ok(mobile.split(/\r?\n/u).length > 80, "mobile bundle should retain periodic line breaks for a phone editor");
});

test("phone transport renders actionable HTTP failure categories", async () => {
  const transport = await read("integrations/messengerbot-r/KLOL_KAKAO_BOT_V41_V2_TRANSPORT.js");
  const context = vm.createContext({ console });
  new vm.Script(transport).runInContext(context);
  const cases = [
    [{ status: 401, body: { code: "KAKAO_INTEGRATION_ERROR" } }, /설치본 인증 오류/u],
    [{ status: 403, body: { code: "INSTALLATION_REVOKED" } }, /회수된 봇 설치본/u],
    [{ status: 403, body: { code: "KAKAO_ROOM_FORBIDDEN" } }, /\/V2연동확인 결과를 관리자에게 전달/u],
    [{ status: 403, body: { code: "KAKAO_CAPABILITY_FORBIDDEN" } }, /이 기능 권한 없음/u],
    [{ status: 400, body: { code: "INVALID_OPERATION_FORM" } }, /양식 필드 누락/u],
    [{ status: 403, body: { code: "ROLE_FORBIDDEN" } }, /이 기능 권한 없음/u],
    [{ status: 400, body: { code: "FORM_INVALID" } }, /양식 필드 누락/u],
    [{ status: 409, body: { code: "CONFLICT" } }, /충돌/u],
  ];
  for (const [result, expected] of cases) {
    context.__result = result;
    assert.match(vm.runInContext("KLOL_V2_KAKAO.userMessage(__result)", context), expected);
  }
});

test("Kakao pending slot lookup is lifecycle-neutral and only cancels ACTIVE rows", async () => {
  const source = await read("src/modules/recruiting/kakao-assistant/postgres-kakao-assistant.ts");
  const start = source.indexOf("const currentPending =");
  const end = source.indexOf("for (const { participant, candidates }", start);
  assert.ok(start > 0 && end > start);
  const reconciliation = source.slice(start, end);
  assert.doesNotMatch(reconciliation, /eq\(seasonKakaoPendingApplications\.status,\s*"ACTIVE"\)/u);
  assert.match(reconciliation, /pending\.status !== "ACTIVE"/u);
  assert.match(source, /planSeasonApplicationMerge\(current \?\? null\)/u);
  assert.match(source, /existingPending\?\.status === "ACTIVE"/u);
  assert.match(source, /status: "ACTIVE" as const[\s\S]*cancelledAt: null,[\s\S]*resolvedAt: null/u);
});
