/**
 * Official Riot Data Dragon champion catalog pinned for deterministic image URLs.
 *
 * Source: https://ddragon.leagueoflegends.com/cdn/16.17.1/data/ko_KR/champion.json
 * Retrieved: 2026-09-10
 */
export const DATA_DRAGON_VERSION = "16.17.1";
export const DATA_DRAGON_CATALOG_SOURCE =
  "https://ddragon.leagueoflegends.com/cdn/" + DATA_DRAGON_VERSION + "/data/ko_KR/champion.json";
export const DATA_DRAGON_EXPECTED_CHAMPION_COUNT = 173;

export type DataDragonChampion = Readonly<{
  riotKey: string;
  id: string;
  name: string;
}>;

export const DATA_DRAGON_CHAMPIONS = Object.freeze([
  { riotKey: "1", id: "Annie", name: "애니" },
  { riotKey: "2", id: "Olaf", name: "올라프" },
  { riotKey: "3", id: "Galio", name: "갈리오" },
  { riotKey: "4", id: "TwistedFate", name: "트위스티드 페이트" },
  { riotKey: "5", id: "XinZhao", name: "신 짜오" },
  { riotKey: "6", id: "Urgot", name: "우르곳" },
  { riotKey: "7", id: "Leblanc", name: "르블랑" },
  { riotKey: "8", id: "Vladimir", name: "블라디미르" },
  { riotKey: "9", id: "Fiddlesticks", name: "피들스틱" },
  { riotKey: "10", id: "Kayle", name: "케일" },
  { riotKey: "11", id: "MasterYi", name: "마스터 이" },
  { riotKey: "12", id: "Alistar", name: "알리스타" },
  { riotKey: "13", id: "Ryze", name: "라이즈" },
  { riotKey: "14", id: "Sion", name: "사이온" },
  { riotKey: "15", id: "Sivir", name: "시비르" },
  { riotKey: "16", id: "Soraka", name: "소라카" },
  { riotKey: "17", id: "Teemo", name: "티모" },
  { riotKey: "18", id: "Tristana", name: "트리스타나" },
  { riotKey: "19", id: "Warwick", name: "워윅" },
  { riotKey: "20", id: "Nunu", name: "누누와 윌럼프" },
  { riotKey: "21", id: "MissFortune", name: "미스 포츈" },
  { riotKey: "22", id: "Ashe", name: "애쉬" },
  { riotKey: "23", id: "Tryndamere", name: "트린다미어" },
  { riotKey: "24", id: "Jax", name: "잭스" },
  { riotKey: "25", id: "Morgana", name: "모르가나" },
  { riotKey: "26", id: "Zilean", name: "질리언" },
  { riotKey: "27", id: "Singed", name: "신지드" },
  { riotKey: "28", id: "Evelynn", name: "이블린" },
  { riotKey: "29", id: "Twitch", name: "트위치" },
  { riotKey: "30", id: "Karthus", name: "카서스" },
  { riotKey: "31", id: "Chogath", name: "초가스" },
  { riotKey: "32", id: "Amumu", name: "아무무" },
  { riotKey: "33", id: "Rammus", name: "람머스" },
  { riotKey: "34", id: "Anivia", name: "애니비아" },
  { riotKey: "35", id: "Shaco", name: "샤코" },
  { riotKey: "36", id: "DrMundo", name: "문도 박사" },
  { riotKey: "37", id: "Sona", name: "소나" },
  { riotKey: "38", id: "Kassadin", name: "카사딘" },
  { riotKey: "39", id: "Irelia", name: "이렐리아" },
  { riotKey: "40", id: "Janna", name: "잔나" },
  { riotKey: "41", id: "Gangplank", name: "갱플랭크" },
  { riotKey: "42", id: "Corki", name: "코르키" },
  { riotKey: "43", id: "Karma", name: "카르마" },
  { riotKey: "44", id: "Taric", name: "타릭" },
  { riotKey: "45", id: "Veigar", name: "베이가" },
  { riotKey: "48", id: "Trundle", name: "트런들" },
  { riotKey: "50", id: "Swain", name: "스웨인" },
  { riotKey: "51", id: "Caitlyn", name: "케이틀린" },
  { riotKey: "53", id: "Blitzcrank", name: "블리츠크랭크" },
  { riotKey: "54", id: "Malphite", name: "말파이트" },
  { riotKey: "55", id: "Katarina", name: "카타리나" },
  { riotKey: "56", id: "Nocturne", name: "녹턴" },
  { riotKey: "57", id: "Maokai", name: "마오카이" },
  { riotKey: "58", id: "Renekton", name: "레넥톤" },
  { riotKey: "59", id: "JarvanIV", name: "자르반 4세" },
  { riotKey: "60", id: "Elise", name: "엘리스" },
  { riotKey: "61", id: "Orianna", name: "오리아나" },
  { riotKey: "62", id: "MonkeyKing", name: "오공" },
  { riotKey: "63", id: "Brand", name: "브랜드" },
  { riotKey: "64", id: "LeeSin", name: "리 신" },
  { riotKey: "67", id: "Vayne", name: "베인" },
  { riotKey: "68", id: "Rumble", name: "럼블" },
  { riotKey: "69", id: "Cassiopeia", name: "카시오페아" },
  { riotKey: "72", id: "Skarner", name: "스카너" },
  { riotKey: "74", id: "Heimerdinger", name: "하이머딩거" },
  { riotKey: "75", id: "Nasus", name: "나서스" },
  { riotKey: "76", id: "Nidalee", name: "니달리" },
  { riotKey: "77", id: "Udyr", name: "우디르" },
  { riotKey: "78", id: "Poppy", name: "뽀삐" },
  { riotKey: "79", id: "Gragas", name: "그라가스" },
  { riotKey: "80", id: "Pantheon", name: "판테온" },
  { riotKey: "81", id: "Ezreal", name: "이즈리얼" },
  { riotKey: "82", id: "Mordekaiser", name: "모데카이저" },
  { riotKey: "83", id: "Yorick", name: "요릭" },
  { riotKey: "84", id: "Akali", name: "아칼리" },
  { riotKey: "85", id: "Kennen", name: "케넨" },
  { riotKey: "86", id: "Garen", name: "가렌" },
  { riotKey: "89", id: "Leona", name: "레오나" },
  { riotKey: "90", id: "Malzahar", name: "말자하" },
  { riotKey: "91", id: "Talon", name: "탈론" },
  { riotKey: "92", id: "Riven", name: "리븐" },
  { riotKey: "96", id: "KogMaw", name: "코그모" },
  { riotKey: "98", id: "Shen", name: "쉔" },
  { riotKey: "99", id: "Lux", name: "럭스" },
  { riotKey: "101", id: "Xerath", name: "제라스" },
  { riotKey: "102", id: "Shyvana", name: "쉬바나" },
  { riotKey: "103", id: "Ahri", name: "아리" },
  { riotKey: "104", id: "Graves", name: "그레이브즈" },
  { riotKey: "105", id: "Fizz", name: "피즈" },
  { riotKey: "106", id: "Volibear", name: "볼리베어" },
  { riotKey: "107", id: "Rengar", name: "렝가" },
  { riotKey: "110", id: "Varus", name: "바루스" },
  { riotKey: "111", id: "Nautilus", name: "노틸러스" },
  { riotKey: "112", id: "Viktor", name: "빅토르" },
  { riotKey: "113", id: "Sejuani", name: "세주아니" },
  { riotKey: "114", id: "Fiora", name: "피오라" },
  { riotKey: "115", id: "Ziggs", name: "직스" },
  { riotKey: "117", id: "Lulu", name: "룰루" },
  { riotKey: "119", id: "Draven", name: "드레이븐" },
  { riotKey: "120", id: "Hecarim", name: "헤카림" },
  { riotKey: "121", id: "Khazix", name: "카직스" },
  { riotKey: "122", id: "Darius", name: "다리우스" },
  { riotKey: "126", id: "Jayce", name: "제이스" },
  { riotKey: "127", id: "Lissandra", name: "리산드라" },
  { riotKey: "131", id: "Diana", name: "다이애나" },
  { riotKey: "133", id: "Quinn", name: "퀸" },
  { riotKey: "134", id: "Syndra", name: "신드라" },
  { riotKey: "136", id: "AurelionSol", name: "아우렐리온 솔" },
  { riotKey: "141", id: "Kayn", name: "케인" },
  { riotKey: "142", id: "Zoe", name: "조이" },
  { riotKey: "143", id: "Zyra", name: "자이라" },
  { riotKey: "145", id: "Kaisa", name: "카이사" },
  { riotKey: "147", id: "Seraphine", name: "세라핀" },
  { riotKey: "150", id: "Gnar", name: "나르" },
  { riotKey: "154", id: "Zac", name: "자크" },
  { riotKey: "157", id: "Yasuo", name: "야스오" },
  { riotKey: "161", id: "Velkoz", name: "벨코즈" },
  { riotKey: "163", id: "Taliyah", name: "탈리야" },
  { riotKey: "164", id: "Camille", name: "카밀" },
  { riotKey: "166", id: "Akshan", name: "아크샨" },
  { riotKey: "200", id: "Belveth", name: "벨베스" },
  { riotKey: "201", id: "Braum", name: "브라움" },
  { riotKey: "202", id: "Jhin", name: "진" },
  { riotKey: "203", id: "Kindred", name: "킨드레드" },
  { riotKey: "221", id: "Zeri", name: "제리" },
  { riotKey: "222", id: "Jinx", name: "징크스" },
  { riotKey: "223", id: "TahmKench", name: "탐 켄치" },
  { riotKey: "233", id: "Briar", name: "브라이어" },
  { riotKey: "234", id: "Viego", name: "비에고" },
  { riotKey: "235", id: "Senna", name: "세나" },
  { riotKey: "236", id: "Lucian", name: "루시안" },
  { riotKey: "238", id: "Zed", name: "제드" },
  { riotKey: "240", id: "Kled", name: "클레드" },
  { riotKey: "245", id: "Ekko", name: "에코" },
  { riotKey: "246", id: "Qiyana", name: "키아나" },
  { riotKey: "254", id: "Vi", name: "바이" },
  { riotKey: "266", id: "Aatrox", name: "아트록스" },
  { riotKey: "267", id: "Nami", name: "나미" },
  { riotKey: "268", id: "Azir", name: "아지르" },
  { riotKey: "350", id: "Yuumi", name: "유미" },
  { riotKey: "360", id: "Samira", name: "사미라" },
  { riotKey: "412", id: "Thresh", name: "쓰레쉬" },
  { riotKey: "420", id: "Illaoi", name: "일라오이" },
  { riotKey: "421", id: "RekSai", name: "렉사이" },
  { riotKey: "427", id: "Ivern", name: "아이번" },
  { riotKey: "429", id: "Kalista", name: "칼리스타" },
  { riotKey: "432", id: "Bard", name: "바드" },
  { riotKey: "497", id: "Rakan", name: "라칸" },
  { riotKey: "498", id: "Xayah", name: "자야" },
  { riotKey: "516", id: "Ornn", name: "오른" },
  { riotKey: "517", id: "Sylas", name: "사일러스" },
  { riotKey: "518", id: "Neeko", name: "니코" },
  { riotKey: "523", id: "Aphelios", name: "아펠리오스" },
  { riotKey: "526", id: "Rell", name: "렐" },
  { riotKey: "555", id: "Pyke", name: "파이크" },
  { riotKey: "711", id: "Vex", name: "벡스" },
  { riotKey: "777", id: "Yone", name: "요네" },
  { riotKey: "799", id: "Ambessa", name: "암베사" },
  { riotKey: "800", id: "Mel", name: "멜" },
  { riotKey: "804", id: "Yunara", name: "유나라" },
  { riotKey: "805", id: "Locke", name: "로크" },
  { riotKey: "875", id: "Sett", name: "세트" },
  { riotKey: "876", id: "Lillia", name: "릴리아" },
  { riotKey: "887", id: "Gwen", name: "그웬" },
  { riotKey: "888", id: "Renata", name: "레나타 글라스크" },
  { riotKey: "893", id: "Aurora", name: "오로라" },
  { riotKey: "895", id: "Nilah", name: "닐라" },
  { riotKey: "897", id: "KSante", name: "크산테" },
  { riotKey: "901", id: "Smolder", name: "스몰더" },
  { riotKey: "902", id: "Milio", name: "밀리오" },
  { riotKey: "904", id: "Zaahen", name: "자헨" },
  { riotKey: "910", id: "Hwei", name: "흐웨이" },
  { riotKey: "950", id: "Naafiri", name: "나피리" },
] satisfies readonly DataDragonChampion[]);
