export type Position = "TOP" | "JGL" | "MID" | "ADC" | "SUP";
export type Team = "RED" | "BLUE";
export type RoleType = "MAIN" | "SUB" | "AUTO";

export type SearchPlayer = {
  id: number;
  name: string;
  nickname: string;
  tag: string;
  currentTier?: string | null;
  peakTier?: string | null;
};

export type PlayerRow = {
  playerId: number | null;
  name: string;
  nickname: string;
  tag: string;
  mainPosition: Position | null;
  mainPositions: Position[];
  subPositions: Position[];
  error: string;
  suggestions: SearchPlayer[];
  searching: boolean;
  selectedLabel: string;
};

export type AssignedPlayer = {
  playerId: number;
  name: string;
  nickname: string;
  tag: string;
  team: Team;
  position: Position;
  roleType: RoleType;
  score: number;
  peakTier: string;
  currentTier: string;
  tierLabel: string;
  winRate: number;
  inhouseScore?: number;
  adjustedScore?: number;
  rankScore?: number;
  rankBaseScore?: number;
  rankAddedScore?: number;
  rankGapFromLowest?: number;
  tierWeight?: number;
  internalRankWeight?: number;
  mixedBaseScore?: number;
  bonus?: number;
  finalBaseScore?: number;
  mainPositions?: Position[];
  subPositions?: Position[];
  currentTierScore?: number;
  peakTierScore?: number;
  baseTierScore?: number;
  recentStats?: {
    games?: number;
    wins?: number;
    winRate?: number | null;
    kda?: number | null;
    mainPosition?: Position | null;
    avgDamage?: number | null;
    avgVisionScore?: number | null;
  };
  internalStats?: {
    totalGames?: number;
    wins?: number;
    losses?: number;
    winRate?: number | null;
    kda?: number | null;
  };
  internalPositionStats?: {
    position?: Position;
    games?: number;
    wins?: number;
    losses?: number;
    winRate?: number | null;
    kda?: number | null;
  };
  balanceOverrideScore?: number;
  balanceOverrideReason?: string | null;
  soloRecentGames?: number;
  soloRecentWins?: number;
  soloRecentWinRate?: number | null;
  soloRecentKda?: number | null;
  soloRecentMainPosition?: Position | null;
  soloRecentSubPosition?: Position | null;
  soloRecentPositionConfidence?: number;
  soloRecentAvgDamage?: number | null;
  soloRecentAvgVisionScore?: number | null;
  internalPositionBonus?: number;
  soloPositionBonus?: number;
  soloApplyPositionMatchBonus?: number;
  positionSkillBonus?: number;
  mmrBonus?: number;
  balanceMmr?: number;
  assignedPositionMmr?: number;
  mmrConfidence?: number;
  rolePenalty?: number;
  soloRecentFormBonus?: number;
  scoreBreakdown?: {
    currentTierScore?: number;
    peakTierScore?: number;
    inhouseScore?: number;
    tierBaseScore?: number;
    adjustedScore?: number;
    tierScore?: number;
    internalRankBaseScore?: number;
    rankGapFromLowest?: number;
    rankAddedScore?: number;
    rankScore?: number;
    tierWeight?: number;
    internalRankWeight?: number;
    mixedBaseScore?: number;
    sTierBonus?: number;
    finalBaseScore?: number;
    roleMultiplier?: number;
    roleLoss?: number;
    rolePenalty?: number;
    recentBonus?: number;
    internalBonus?: number;
    soloRecentFormBonus?: number;
    soloApplyPositionMatchBonus?: number;
    internalPositionBonus?: number;
    soloPositionBonus?: number;
    positionSkillBonus?: number;
    mmrBonus?: number;
    balanceOverrideScore?: number;
    finalScore?: number;
  };
  explanation?: string[];
};

export type BalanceResponse = {
  optionNo?: number;
  optionTitle?: string;
  optionDescription?: string;
  planType?: "TEAM_TOTAL" | "LINE_BALANCE" | "POSITION_SATISFACTION";
  planCost?: number;
  redTotal: number;
  blueTotal: number;
  diff: number;
  balanceCost?: number;
  qualityScore?: number;
  recommendationScore?: number;
  warningMessages?: string[];
  lineDiffTotal?: number;
  maxLineDiff?: number;
  topPlayerDiff?: number;
  sTierStackPenalty?: number;
  weightedLineDiff?: number;
  frontSideDiff?: number;
  midJglDiff?: number;
  bottomDiff?: number;
  autoLinePenalty?: number;
  mainImbalancePenalty?: number;
  dataReliabilityPenalty?: number;
  stompPenalty?: number;
  mainAssignedCount: number;
  subAssignedCount: number;
  autoAssignedCount: number;
  red: AssignedPlayer[];
  blue: AssignedPlayer[];
  soloSync?: {
    requested: number;
    synced: number;
    skipped: number;
    failed: number;
    results?: Array<{ playerId?: number; status?: string; reason?: string; message?: string }>;
  } | null;
  recommendedAlternative?: {
    optionNo?: number;
    optionTitle?: string;
    qualityScore?: number;
    recommendationScore?: number;
    reason?: string;
  } | null;
  aiJudgement?: {
    selectedOptionNo: number | null;
    selectedOptionTitle: string | null;
    confidence: number;
    riskLevel: "LOW" | "MEDIUM" | "HIGH";
    verdict: string;
    inferredWinner: "RED" | "BLUE" | "EVEN";
    predictedRedWinRate: number;
    predictedBlueWinRate: number;
    reasoning: string[];
    riskFactors: string[];
    strengthFactors?: string[];
    improvementSuggestions?: string[];
    laneFocus?: string;
    draftNotes?: string[];
    dataWarnings?: string[];
    overallSummary?: string;
    operatingAdvice: string;
  } | null;
  aiBestAlternative?: BalanceResponse | null;
  aiCandidateCount?: number;
  aiSearchScope?: "ALL_CANDIDATES" | "THREE_OPTIONS";
  serverEvaluationMode?: "AUTO" | "MANUAL_RECALCULATED" | "MANUAL_ESTIMATE";
  alternatives?: BalanceResponse[];
};
export type ApplyPosition = Position | "ALL";

export type SeasonApplyPlayer = {
  playerId: number;
  name: string;
  nickname: string;
  tag: string;
  peakTier: string | null;
  currentTier: string | null;
  mainPosition: ApplyPosition | null;
  subPositions: ApplyPosition[];
};

export type SeasonApplyGroup = {
  key: string;
  label: string;
  applyDate: string;
  recruitNo: number;
  order: number;
  count: number;
  players: SeasonApplyPlayer[];
};

export type ErrorResponse = {
  message: string;
  invalidNames?: string[];
};
