export type Diagnostic = { level: "OK" | "INFO" | "WARN" | "ERROR"; code: string; title: string; message: string; action?: string };
export type DiscordSettings = {
  autoFinishEnabled: boolean;
  autoFinishHoldMinutes: number;
  recruitLateWarningEnabled: boolean;
  recruitLateWarningGraceMinutes: number;
  recruitLateWarningDmEnabled: boolean;
  watchAllVoiceChannels: boolean;
  watchChannelIds: string[];
  watchCategoryIds: string[];
  adminLogChannelId: string | null;
  noticeChannelId: string | null;
  recruitLogChannelId: string | null;
  approvedRoleId: string | null;
  topRoleId: string | null;
  jglRoleId: string | null;
  midRoleId: string | null;
  adcRoleId: string | null;
  supRoleId: string | null;
  heartbeatIntervalSeconds: number;
  staleHeartbeatSeconds: number;
};
export type Overview = {
  summary: {
    approvedUsers: number;
    linkedUsers: number;
    unlinkedApprovedUsers: number;
    linkRate: number;
    recentEventCount: number;
    currentVoiceUserCount: number;
    currentLinkedVoiceUserCount: number;
    currentUnlinkedVoiceUserCount: number;
    activeMonitorCount: number;
    healthyBotCount: number;
    recruitReadyCount: number;
    recruitNeedsCheckCount: number;
    matchAttendancePresentCount: number;
    matchAttendanceTotalCount: number;
    matchAttendanceLateCount: number;
    matchAttendanceAbsentWarningCount: number;
  };
  settings: DiscordSettings;
  heartbeats: Array<{ botId: string; status: string; botUsername: string | null; updatedAt: string; uptimeSeconds: number; memoryRssMb: number | null; voiceMemberCount: number; autoFinishEnabled: boolean; lastError: string | null }>;
  currentVoiceUsers: Array<{ id: number; discordId: string; eventType: string; channelName: string | null; memberDisplayName: string | null; memberNickname: string | null; discordUsername: string | null; discordGlobalName: string | null; occurredAt: string; userAccountId: number | null; userAccount?: { userId: string; discordServerNickname: string | null; discordGlobalName: string | null; discordUsername: string | null; player: { name: string | null; nickname: string; tag: string } | null } | null }>;
  matchAttendance: {
    totalCount: number;
    presentCount: number;
    lateCount: number;
    absentWarningCount: number;
    waitingCount: number;
    unlinkedCount: number;
    matchStartText?: string;
    requiredArrivalText?: string;
    absentAfterText?: string;
    players: Array<{ applyId: number; playerId: number; name: string; nickname: string; tag: string; linked: boolean; present: boolean; matchType: string; attendanceStatus: string; matchedDisplayName: string | null; channelName: string | null; joinedAt: string | null }>;
    extraVoiceUsers: Array<{ discordId: string; displayName: string; channelName: string | null }>;
  };
  autoFinishedRecruitMonitors: Array<{
    monitorId: number;
    partyId: number;
    recruitNo: number;
    title: string;
    type: string;
    partyStatus: string;
    maxMembers: number;
    recruitDate: string | null;
    startTimeText: string | null;
    participantNames: string[];
    voiceChannelId: string | null;
    voiceChannelName: string | null;
    status: string;
    lastExpectedCount: number;
    lastPresentExpectedCount: number;
    lastNonParticipantCount: number;
    finishCandidateStartedAt: string | null;
    autoFinishedAt: string | null;
    autoFinishReason: string | null;
    updatedAt: string;
  }>;
  recruitVerifications: Array<{
    partyId: number;
    recruitNo: number;
    title: string;
    type: string;
    status: string;
    partyStatus: string;
    maxMembers: number;
    activeMemberCount: number;
    linkedCount: number;
    presentCount: number;
    matchedByNameCount: number;
    ambiguousCount: number;
    missingCount: number;
    unlinkedCount: number;
    nonParticipantCount: number;
    nonParticipantDisplayNames: string[];
    scenarioLabels: string[];
    guessedChannelNames: string[];
    voiceChannelId: string | null;
    monitorStatus: string | null;
    monitorChannelId?: string | null;
    channelReestimated?: boolean;
    lastScannedAt: string | null;
    finishCandidateStartedAt: string | null;
    autoFinishedAt: string | null;
    autoFinishReason: string | null;
    presentParticipants: string[];
    missingParticipants: string[];
    unlinkedParticipants: string[];
  }>;
  linkLogs: Array<{ id: number; action: string; discordId: string | null; discordServerNickname: string | null; discordGlobalName: string | null; discordUsername: string | null; reason: string | null; createdAt: string; userAccount: { userId: string; player: { name: string | null; nickname: string; tag: string } | null } | null }>;
  diagnostics?: Diagnostic[];
};
