import { AuctionReveal } from "./auction-reveal";
import { DESTRUCTION_GAME_MODES } from "@/modules/competitions/destruction/aram-rating";
import type { DestructionPublicDto } from "@/modules/competitions/destruction/state";
import { DESTRUCTION_STATUS_LABEL } from "@/modules/competitions/destruction/workflow";
import { competitionPositionLabel } from "@/modules/competitions/core/display-projection";
import { DestructionLiveStatus } from "./live-status";
import styles from "./workspace.module.css";
import { DESTRUCTION_SCHEDULE_LABELS } from "@/modules/competitions/destruction/schedule";

export function DestructionPublicProgress({ destruction }: { destruction: DestructionPublicDto }) {
  return <section className={styles.workspace} aria-label="지금 대회에서 할 일"><div className={styles.callout}><h2>{DESTRUCTION_GAME_MODES[destruction.gameMode]} 멸망전 · {DESTRUCTION_STATUS_LABEL[destruction.status]}</h2>{destruction.status === "RECRUITING" ? <a href="#destruction-application">내 참가 신청 확인</a> : ["PRELIMINARY", "TOURNAMENT"].includes(destruction.status) ? <a href="#destruction-mvp">내 MVP 투표 확인</a> : null}<DestructionLiveStatus tournamentId={destruction.id} revision={destruction.revision} enabled={destruction.status !== "COMPLETED"} /></div>
    <details className={styles.panel}><summary>예정 일정 · 한국 시간</summary>{Object.entries(DESTRUCTION_SCHEDULE_LABELS).map(([key, label]) => { const instant = destruction.schedule[key as keyof typeof destruction.schedule]; return <p className={styles.row} key={key}><span>{label}</span><strong>{instant ? new Intl.DateTimeFormat("ko-KR", { timeZone: "Asia/Seoul", dateStyle: "medium", timeStyle: "short" }).format(new Date(instant)) : "미정"}</strong></p>; })}</details>
    {["PLANNED", "RECRUITING", "TEAM_BUILDING"].includes(destruction.status) ? <section className={styles.panel}><h2>{destruction.gameMode === "CLASSIC" ? "포지션별 모집 현황" : "전체 모집 현황"}</h2><div className={styles.lanes}>{destruction.recruitment.map((lane) => <article key={lane.position ?? "ALL"}><span>{lane.position ? competitionPositionLabel(lane.position) : "전체 인원"}</span><strong>{lane.applied}/{lane.limit}</strong><small>신청 / 모집 상한</small><small>참가 확정 {lane.confirmed}/{lane.required}명</small></article>)}</div></section> : null}
    {destruction.status === "AUCTION" ? <section className={styles.callout}><h2>경매 {destruction.auction.paused ? "일시 중단" : "진행 현황"}</h2><AuctionReveal card={destruction.auction.card} /><strong>{destruction.auction.drawnPlayerName ? `${destruction.auction.drawnPlayerName}${destruction.gameMode === "CLASSIC" ? ` · ${competitionPositionLabel(destruction.auction.drawnPosition ?? "")}` : ""}` : "다음 선수 추첨 대기"}</strong><p>낙찰 {destruction.auction.soldCount}명 · 경매 대기 {destruction.auction.pendingCount}명</p></section> : null}
  </section>;
}

export function DestructionRulesAndStandings({ destruction }: { destruction: DestructionPublicDto }) {
  const complete = destruction.preliminaryFixtures.length > 0 && destruction.preliminaryFixtures.every((fixture) => fixture.confirmed);
  return <section className={styles.workspace} aria-label="대회 규칙과 예선 순위">
    {destruction.standings.length ? <section className={styles.panel}><h2>예선 순위 · {complete ? "결과 확정" : "진행 중"}</h2><p>집계: 확정 경기 · 정렬: 승점(승리 1점) → 승수 → 적은 패수 → 팀 식별자 · 세트 득실: 참고 · {destruction.preliminaryFormat.startsWith("GROUP_") ? "진출: 조별 상위 2팀" : "진출: 상위 4팀"}</p>{destruction.standings.map((group) => <div className={styles.tableWrap} key={group.groupKey ?? "all"}><table><caption>{group.groupKey ? `${group.groupKey}조` : "전체 순위"} · {complete ? "예선 최종" : "잠정 순위"}</caption><thead><tr><th>순위</th><th>팀</th><th>경기</th><th>승</th><th>패</th><th>승점</th><th>세트 득실</th></tr></thead><tbody>{group.rows.map((row) => <tr key={row.teamId}><td>{row.rank}</td><th scope="row">{row.teamName}{destruction.qualifiedTeamIds.includes(row.teamId) ? " · 본선 진출" : ""}</th><td>{row.played}</td><td>{row.wins}</td><td>{row.losses}</td><td>{row.points}</td><td>{row.setsFor} : {row.setsAgainst}</td></tr>)}</tbody></table></div>)}</section> : null}
    {destruction.gameMode !== "CLASSIC" && !destruction.ratingPolicy && destruction.teams.length > 0 ? <section className={styles.panel}><h2>대회 임시 등급 · 최근 최대 100판</h2><p>대회 경매용 임시 등급 · Riot 공식 티어·MMR 아님. 보정 승률 = (승수 + 10) / (판수 + 20). 20판 미만: 잠정 B. S ≥ 60%, A ≥ 52.5%, B ≥ 47.5%, C ≥ 40%, D &lt; 40%. 최소 입찰가: S 300P · A 250P · B 200P · C 150P · D 100P. 주장 보유금: 2,000P − 본인 최소 입찰가. 50판 미만: 표본 부족. 주장 확정 후 평가 고정.</p>{destruction.auctionRatings.map((r, i) => <p key={i}>{r.playerName} · {r.tier}등급 · {r.games}판 {r.wins}승 {r.losses}패 · 최소 {r.minimumBid}P · {r.source === "RIOT" ? "Riot 조회" : "운영자 확인"}{r.provisional ? " · 표본 부족" : ""}</p>)}</section> : null}<details className={styles.panel}><summary>참가·경매·경기 규칙</summary><ul className={styles.blockers}><li>{destruction.teamCount}팀 · 팀당 5명 · {destruction.gameMode === "CLASSIC" ? "포지션별 1명" : "포지션 구분 없음"}</li><li>참가 조건: 승인 계정·활성 선수 연결</li><li>참가 확정 후 변경: 운영자 문의</li>{destruction.gameMode === "CLASSIC" ? <><li>주장 시작 포인트: 2,000 − 기준 가치 × 10, 10P 단위 반올림, 0~2,000P 제한</li><li>최소 낙찰 1P · 남은 선수 충원에 필요한 최소 포인트 보존</li></> : <li>임시 등급별 최소 입찰가 적용 · 남은 선수를 충원할 최소 포인트 보존</li>}<li>예선 BO{destruction.preliminaryBestOf} · 본선 4강·결승 BO3</li><li>MVP 투표: 해당 경기 선수 10명 · 본인 투표 불가</li></ul>{/^(SWISS|RANDOM)_/.test(destruction.preliminaryFormat) ? <p>고정 대진 · 승점에 따른 상대 재배정 없음</p> : null}</details>
  </section>;
}
