import { AuctionReveal } from "./auction-reveal";
import { DESTRUCTION_GAME_MODES } from "@/modules/competitions/destruction/aram-rating";
import type { DestructionPublicDto } from "@/modules/competitions/destruction/state";
import { DESTRUCTION_STAGE_HELP, DESTRUCTION_STATUS_LABEL } from "@/modules/competitions/destruction/workflow";
import { competitionPositionLabel } from "@/modules/competitions/core/display-projection";
import { DestructionLiveStatus } from "./live-status";
import styles from "./workspace.module.css";
import { DESTRUCTION_SCHEDULE_LABELS } from "@/modules/competitions/destruction/schedule";

export function DestructionPublicProgress({ destruction }: { destruction: DestructionPublicDto }) {
  return <section className={styles.workspace} aria-label="지금 대회에서 할 일"><div className={styles.callout}><h2>{DESTRUCTION_GAME_MODES[destruction.gameMode]} 멸망전 · {DESTRUCTION_STATUS_LABEL[destruction.status]}</h2><p>{DESTRUCTION_STAGE_HELP[destruction.status]}</p>{destruction.status === "RECRUITING" ? <a href="#destruction-application">내 참가 신청 확인</a> : ["PRELIMINARY", "TOURNAMENT"].includes(destruction.status) ? <a href="#destruction-mvp">내 MVP 투표 확인</a> : null}<DestructionLiveStatus tournamentId={destruction.id} revision={destruction.revision} enabled={destruction.status !== "COMPLETED"} /></div>
    <details className={styles.panel}><summary>대회 일정 · 한국 시간</summary>{Object.entries(DESTRUCTION_SCHEDULE_LABELS).map(([key, label]) => { const instant = destruction.schedule[key as keyof typeof destruction.schedule]; return <p className={styles.row} key={key}><span>{label}</span><strong>{instant ? new Intl.DateTimeFormat("ko-KR", { timeZone: "Asia/Seoul", dateStyle: "medium", timeStyle: "short" }).format(new Date(instant)) : "미정"}</strong></p>; })}<p>예정 일정은 운영 상황에 따라 변경될 수 있습니다. 현재 진행 단계는 위의 대회 현황에서 확인하세요.</p></details>
    {["PLANNED", "RECRUITING", "TEAM_BUILDING"].includes(destruction.status) ? <section className={styles.panel}><h2>포지션별 모집 현황</h2><div className={styles.lanes}>{destruction.recruitment.map((lane) => <article key={lane.position}><span>{competitionPositionLabel(lane.position)}</span><strong>{lane.applied}/{lane.limit}</strong><small>신청 / 모집 상한</small><small>참가 확정 {lane.confirmed}/{lane.required}명</small></article>)}</div></section> : null}
    {destruction.status === "AUCTION" ? <section className={styles.callout}><h2>경매 {destruction.auction.paused ? "일시 중단" : "진행 현황"}</h2><AuctionReveal card={destruction.auction.card} /><strong>{destruction.auction.drawnPlayerName ? `${destruction.auction.drawnPlayerName} · ${competitionPositionLabel(destruction.auction.drawnPosition ?? "")}` : "다음 선수 추첨 대기"}</strong><p>낙찰 {destruction.auction.soldCount}명 · 경매 대기 {destruction.auction.pendingCount}명</p><p>운영자가 낙찰을 확정하면 팀과 잔여 포인트에 반영됩니다.</p></section> : null}
  </section>;
}

export function DestructionRulesAndStandings({ destruction }: { destruction: DestructionPublicDto }) {
  const complete = destruction.preliminaryFixtures.length > 0 && destruction.preliminaryFixtures.every((fixture) => fixture.confirmed);
  return <section className={styles.workspace} aria-label="대회 규칙과 예선 순위">
    {destruction.standings.length ? <section className={styles.panel}><h2>예선 순위 · {complete ? "결과 확정" : "진행 중"}</h2><p>확정 경기만 집계합니다. 승점(승리 1점) → 승수 → 적은 패수 → 기존 팀 식별자 순으로 정렬합니다. 세트 득실은 참고 지표입니다. {destruction.preliminaryFormat.startsWith("GROUP_") ? "각 조 상위 2팀이 진출합니다." : "상위 4팀이 진출합니다."}</p>{destruction.standings.map((group) => <div className={styles.tableWrap} key={group.groupKey ?? "all"}><table><caption>{group.groupKey ? `${group.groupKey}조` : "전체 순위"} · {complete ? "예선 최종" : "잠정 순위"}</caption><thead><tr><th>순위</th><th>팀</th><th>경기</th><th>승</th><th>패</th><th>승점</th><th>세트 득실</th></tr></thead><tbody>{group.rows.map((row) => <tr key={row.teamId}><td>{row.rank}</td><th scope="row">{row.teamName}{destruction.qualifiedTeamIds.includes(row.teamId) ? " · 본선 진출" : ""}</th><td>{row.played}</td><td>{row.wins}</td><td>{row.losses}</td><td>{row.points}</td><td>{row.setsFor} : {row.setsAgainst}</td></tr>)}</tbody></table></div>)}</section> : null}
    {destruction.gameMode !== "CLASSIC" ? <section className={styles.panel}><h2>대회 임시 등급 · 최근 최대 100판</h2><p>이 대회의 경매 편성을 위한 등급이며 Riot 공식 티어·MMR이 아닙니다. 보정 승률 = (승수 + 10) / (판수 + 20). 20판 미만은 승률에 관계없이 잠정 B등급입니다. S ≥ 60%, A ≥ 52.5%, B ≥ 47.5%, C ≥ 40%, D &lt; 40%. 최소 입찰가는 S 300P · A 250P · B 200P · C 150P · D 100P, 주장 보유금은 2,000P − 본인 최소 입찰가입니다. 50판 미만은 표본 부족으로 표시합니다. 주장 확정 이후 평가를 고정합니다.</p>{destruction.auctionRatings.map((r, i) => <p key={i}>{r.playerName} · {r.tier}등급 · {r.games}판 {r.wins}승 {r.losses}패 · 최소 {r.minimumBid}P · {r.source === "RIOT" ? "Riot 조회" : "운영자 확인"}{r.provisional ? " · 표본 부족" : ""}</p>)}</section> : null}<details className={styles.panel}><summary>참가·경매·경기 규칙</summary><ul className={styles.blockers}><li>{destruction.teamCount}팀 · 팀당 5명 · 포지션별 1명</li><li>승인된 계정에 연결된 활성 선수만 참가 신청할 수 있습니다.</li><li>참가 확정 이후 신청 변경은 운영자에게 요청해 주세요.</li>{destruction.gameMode === "CLASSIC" ? <><li>주장 시작 포인트: 2,000 − 기준 가치 × 10, 10P 단위 반올림, 0~2,000P 제한</li><li>최소 낙찰 1P · 남은 선수 충원에 필요한 최소 포인트 보존</li></> : <li>임시 등급별 최소 입찰가 적용 · 남은 포지션을 충원할 최소 포인트 보존</li>}<li>예선 BO{destruction.preliminaryBestOf} · 본선 4강·결승 BO3</li><li>MVP는 해당 경기의 선수 10명이 투표하며 본인에게 투표할 수 없습니다.</li></ul>{/^(SWISS|RANDOM)_/.test(destruction.preliminaryFormat) ? <p>이 대회의 라운드는 기존 고정 대진 규칙을 사용합니다. 승점에 따라 다음 상대를 다시 배정하지 않습니다.</p> : null}</details>
  </section>;
}
