ALTER TABLE "UserAccount" ADD COLUMN IF NOT EXISTS "adminTotpSecret" TEXT;
ALTER TABLE "UserAccount" ADD COLUMN IF NOT EXISTS "adminTotpEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "UserAccount" ADD COLUMN IF NOT EXISTS "adminTotpEnabledAt" TIMESTAMP(3);
ALTER TABLE "UserAccount" ADD COLUMN IF NOT EXISTS "adminTotpLastUsedStep" BIGINT;
