ALTER TABLE "DestructionTournament"
ADD COLUMN "topLaneLimit" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN "jungleLaneLimit" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN "midLaneLimit" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN "adcLaneLimit" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN "supportLaneLimit" INTEGER NOT NULL DEFAULT 10;
