import { definePublicProblem, type PublicProblemDefinition } from "@/platform/http";
import type { AccountConflictReason } from "../domain/account-contracts";

export const ACCOUNT_HTTP_PROBLEMS = Object.freeze({
  unauthorized: definePublicProblem({ code: "ACCOUNT_AUTH_REQUIRED", status: 401, title: "로그인이 필요합니다.", detail: "일반 계정으로 다시 로그인해 주세요." }),
  sessionStale: definePublicProblem({ code: "ACCOUNT_SESSION_STALE", status: 401, title: "세션 상태가 변경되었습니다.", detail: "안전한 처리를 위해 다시 로그인해 주세요." }),
  forbidden: definePublicProblem({ code: "ACCOUNT_ACTION_FORBIDDEN", status: 403, title: "이 작업을 수행할 권한이 없습니다.", detail: "현재 계정 역할과 상태를 확인해 주세요." }),
  originForbidden: definePublicProblem({ code: "ACCOUNT_ORIGIN_FORBIDDEN", status: 403, title: "허용되지 않은 요청 출처입니다.", detail: "현재 사이트에서 다시 시도해 주세요." }),
  invalidInput: definePublicProblem({ code: "ACCOUNT_INPUT_INVALID", status: 400, title: "입력값을 확인해 주세요.", detail: "필수 항목과 허용된 형식을 확인한 뒤 다시 시도해 주세요." }),
  invalidQuery: definePublicProblem({ code: "ACCOUNT_QUERY_INVALID", status: 400, title: "조회 조건이 올바르지 않습니다.", detail: "검색어와 상태·역할·페이지 조건을 확인해 주세요." }),
  invalidCredentials: definePublicProblem({ code: "ACCOUNT_CREDENTIALS_INVALID", status: 401, title: "로그인할 수 없습니다.", detail: "아이디 또는 비밀번호를 확인해 주세요." }),
  invalidCurrentPassword: definePublicProblem({ code: "CURRENT_PASSWORD_INVALID", status: 400, title: "현재 비밀번호가 올바르지 않습니다.", detail: "현재 비밀번호를 다시 확인해 주세요." }),
  notFound: definePublicProblem({ code: "ACCOUNT_NOT_FOUND", status: 404, title: "계정을 찾을 수 없습니다.", detail: "주소 또는 계정 식별자를 확인해 주세요." }),
  conflict: definePublicProblem({ code: "ACCOUNT_CONFLICT", status: 409, title: "현재 상태에서는 처리할 수 없습니다.", detail: "계정·플레이어 상태를 새로 확인한 뒤 다시 시도해 주세요." }),
  loginIdExists: definePublicProblem({ code: "LOGIN_ID_EXISTS", status: 409, title: "이미 사용 중인 아이디입니다.", detail: "다른 아이디를 사용해 주세요." }),
  riotIdLinked: definePublicProblem({ code: "RIOT_ID_ALREADY_LINKED", status: 409, title: "이미 다른 계정에 연결된 Riot ID입니다.", detail: "본인의 Riot ID인지 확인하거나 관리자에게 문의해 주세요." }),
  idempotencyConflict: definePublicProblem({ code: "IDEMPOTENCY_KEY_REUSED", status: 409, title: "같은 요청 키가 다른 내용에 사용되었습니다.", detail: "요청 내용을 새로 고친 뒤 다시 시도해 주세요." }),
  oneTimeSecretIssued: definePublicProblem({ code: "ONE_TIME_SECRET_ALREADY_ISSUED", status: 409, title: "임시 비밀번호는 다시 표시할 수 없습니다.", detail: "필요하면 새 멱등성 키로 임시 비밀번호를 다시 발급해 주세요." }),
  playerClaimTaken: definePublicProblem({ code: "PLAYER_CLAIM_TAKEN", status: 409, title: "다른 계정이 이 플레이어 연결을 먼저 요청했습니다.", detail: "요청한 계정 상태 변경은 반영되지 않았습니다. 경쟁 claim을 검토·해결한 뒤 다시 시도해 주세요." }),
  activePlayerRequired: definePublicProblem({ code: "ACTIVE_PLAYER_REQUIRED", status: 409, title: "승인 가능한 활성 플레이어가 필요합니다.", detail: "연결 대상이 없거나 운영상 독립 비활성 상태입니다. 플레이어 관리에서 대상과 비활성 사유를 확인하고, 필요한 경우 명시적으로 재활성화한 뒤 승인을 다시 시도해 주세요." }),
  playerClaimPending: definePublicProblem({ code: "PLAYER_CLAIM_PENDING", status: 409, title: "이미 검토 중인 플레이어 연결 요청입니다.", detail: "관리자 검토가 끝난 뒤 다시 확인하거나 다른 Riot ID를 사용해 주세요." }),
  targetConfirmationMismatch: definePublicProblem({ code: "TARGET_CONFIRMATION_MISMATCH", status: 409, title: "대상 계정 확인값이 일치하지 않습니다.", detail: "최신 계정 아이디를 정확히 다시 입력해 주세요." }),
  accountDeleted: definePublicProblem({ code: "ACCOUNT_DELETED", status: 409, title: "삭제된 계정에는 이 작업을 수행할 수 없습니다.", detail: "필요하면 먼저 계정을 복구한 뒤 최신 상태에서 다시 시도해 주세요." }),
  statusUnchanged: definePublicProblem({ code: "STATUS_UNCHANGED", status: 409, title: "이미 선택한 계정 상태입니다.", detail: "최신 상태를 확인하고 다른 전이를 선택해 주세요." }),
  playerClaimAckRequired: definePublicProblem({ code: "PLAYER_CLAIM_ACK_REQUIRED", status: 409, title: "플레이어 연결 수동 검토 확인이 필요합니다.", detail: "대상 플레이어와 가입 입력을 다시 대조하고 명시적 확인란을 선택해 주세요." }),
  playerClaimStateChanged: definePublicProblem({ code: "PLAYER_CLAIM_STATE_CHANGED", status: 409, title: "플레이어 연결 요청 상태가 변경되었습니다.", detail: "계정 상세를 새로 불러와 현재 claim 대상과 상태를 다시 검토해 주세요." }),
  roleUnchanged: definePublicProblem({ code: "ROLE_UNCHANGED", status: 409, title: "이미 선택한 계정 역할입니다.", detail: "최신 역할을 확인하고 다른 역할을 선택해 주세요." }),
  adminEligibility: definePublicProblem({ code: "ADMIN_ELIGIBILITY", status: 409, title: "관리자 역할 요건을 충족하지 않습니다.", detail: "승인된 활성 계정인지 확인한 뒤 다시 시도해 주세요." }),
  totpNotConfigured: definePublicProblem({ code: "TOTP_NOT_CONFIGURED", status: 409, title: "초기화할 관리자 2단계 인증이 없습니다.", detail: "대상의 현재 2단계 인증 상태를 새로 확인해 주세요." }),
  alreadyDeleted: definePublicProblem({ code: "ALREADY_DELETED", status: 409, title: "이미 삭제된 계정입니다.", detail: "삭제 목록에서 최신 상태를 확인하고 복구 작업을 사용해 주세요." }),
  notDeleted: definePublicProblem({ code: "NOT_DELETED", status: 409, title: "삭제되지 않은 계정은 복구할 수 없습니다.", detail: "활성 계정 목록에서 최신 상태를 확인해 주세요." }),
  revisionMismatch: definePublicProblem({ code: "ACCOUNT_REVISION_MISMATCH", status: 412, title: "계정 정보가 이미 변경되었습니다.", detail: "최신 계정 정보를 불러온 뒤 다시 시도해 주세요." }),
  rateLimited: definePublicProblem({ code: "ACCOUNT_ATTEMPTS_LIMITED", status: 429, title: "요청이 너무 많습니다.", detail: "잠시 후 다시 시도해 주세요." }),
  unavailable: definePublicProblem({ code: "ACCOUNT_STORAGE_UNAVAILABLE", status: 503, title: "계정 저장소를 사용할 수 없습니다.", detail: "잠시 후 다시 시도해 주세요." }),
});

export const ACCOUNT_CONFLICT_PROBLEM_BY_REASON = Object.freeze({
  ACCOUNT_DELETED: ACCOUNT_HTTP_PROBLEMS.accountDeleted,
  ACTIVE_PLAYER_REQUIRED: ACCOUNT_HTTP_PROBLEMS.activePlayerRequired,
  ADMIN_ELIGIBILITY: ACCOUNT_HTTP_PROBLEMS.adminEligibility,
  ALREADY_DELETED: ACCOUNT_HTTP_PROBLEMS.alreadyDeleted,
  IDEMPOTENCY_KEY_REUSED: ACCOUNT_HTTP_PROBLEMS.idempotencyConflict,
  LOGIN_ID_EXISTS: ACCOUNT_HTTP_PROBLEMS.loginIdExists,
  NOT_DELETED: ACCOUNT_HTTP_PROBLEMS.notDeleted,
  ONE_TIME_SECRET_ALREADY_ISSUED: ACCOUNT_HTTP_PROBLEMS.oneTimeSecretIssued,
  PLAYER_CLAIM_ACK_REQUIRED: ACCOUNT_HTTP_PROBLEMS.playerClaimAckRequired,
  PLAYER_CLAIM_PENDING: ACCOUNT_HTTP_PROBLEMS.playerClaimPending,
  PLAYER_CLAIM_STATE_CHANGED: ACCOUNT_HTTP_PROBLEMS.playerClaimStateChanged,
  PLAYER_CLAIM_TAKEN: ACCOUNT_HTTP_PROBLEMS.playerClaimTaken,
  RIOT_ID_ALREADY_LINKED: ACCOUNT_HTTP_PROBLEMS.riotIdLinked,
  ROLE_UNCHANGED: ACCOUNT_HTTP_PROBLEMS.roleUnchanged,
  STATUS_UNCHANGED: ACCOUNT_HTTP_PROBLEMS.statusUnchanged,
  TARGET_CONFIRMATION_MISMATCH: ACCOUNT_HTTP_PROBLEMS.targetConfirmationMismatch,
  TOTP_NOT_CONFIGURED: ACCOUNT_HTTP_PROBLEMS.totpNotConfigured,
} satisfies Record<AccountConflictReason, PublicProblemDefinition>);
