/* GENERATED by scripts/build-messengerbot-v41.mjs. Edit TRANSPORT or ROUTER, then rebuild. */
/* eslint-disable */
/*
 * K-LOL.GG MessengerBot R V2 transport adapter.
 *
 * This file intentionally does not define response(). Use it with the V41
 * router, or paste the generated KLOL_KAKAO_BOT_V41_V2_COMPLETE.js into
 * MessengerBot R as the standalone bot entry.
 *
 * Never place the signing secret in source. Store it only in MessengerBot R's
 * private DataBase under KLOL_V2_KAKAO_WEBHOOK_SECRET_CURRENT. Keep the stable
 * pseudonymous-ID key under KLOL_V2_KAKAO_IDENTITY_SECRET.
 */
var KLOL_V2_KAKAO = (function () {
  var CONTRACT_VERSION = "KLOL_KAKAO_WEBHOOK_V1";
  var DEFAULT_BASE_URL = "https://k-lol-gg.vercel.app";
  var SETTING_BASE_URL = "KLOL_V2_BASE_URL";
  var SETTING_SIGNING_SECRET = "KLOL_V2_KAKAO_WEBHOOK_SECRET_CURRENT";
  var SETTING_IDENTITY_SECRET = "KLOL_V2_KAKAO_IDENTITY_SECRET";
  var ENDPOINTS = {
    recruit: "/api/integrations/kakao/recruits",
    playerSearch: "/api/integrations/kakao/search-player",
    openchat: "/api/integrations/kakao/openchat",
    seasonApplications: "/api/integrations/kakao/season-applications",
    managedForms: "/api/integrations/kakao/managed-forms",
    operationForms: "/api/integrations/kakao/operation-forms",
    imageReceive: "/api/integrations/kakao/image-receive",
    scheduledNotice: "/api/integrations/kakao/scheduled-notice"
  };

  function trimText(value) {
    return String(value == null ? "" : value).replace(/^\s+|\s+$/g, "");
  }

  function readPrivateSetting(key) {
    try {
      return trimText(String(DataBase.getDataBase(key) || ""));
    } catch (ignored) {
      return "";
    }
  }

  function utf8(value) {
    return new java.lang.String(String(value)).getBytes(java.nio.charset.StandardCharsets.UTF_8);
  }

  function bytesToHex(bytes) {
    var builder = new java.lang.StringBuilder(bytes.length * 2);
    for (var index = 0; index < bytes.length; index += 1) {
      var unsigned = bytes[index] & 255;
      if (unsigned < 16) builder.append("0");
      builder.append(java.lang.Integer.toHexString(unsigned));
    }
    return String(builder.toString());
  }

  function sha256Hex(value) {
    var digest = java.security.MessageDigest.getInstance("SHA-256");
    return bytesToHex(digest.digest(utf8(value)));
  }

  function sha256Base64BytesHex(value) {
    var decoded = android.util.Base64.decode(String(value), android.util.Base64.DEFAULT);
    var digest = java.security.MessageDigest.getInstance("SHA-256");
    return bytesToHex(digest.digest(decoded));
  }

  function hmacSha256Hex(secret, value) {
    var mac = javax.crypto.Mac.getInstance("HmacSHA256");
    mac.init(new javax.crypto.spec.SecretKeySpec(utf8(secret), "HmacSHA256"));
    return bytesToHex(mac.doFinal(utf8(value)));
  }

  function normalizeBaseUrl(value) {
    var baseUrl = trimText(value || DEFAULT_BASE_URL).replace(/\/+$/, "");
    if (!/^https:\/\/[A-Za-z0-9](?:[A-Za-z0-9.-]{0,251}[A-Za-z0-9])?(?::443)?$/.test(baseUrl)) {
      throw new Error("V2 HTTPS 주소 설정을 확인해 주세요.");
    }
    return baseUrl;
  }

  function safeIdentifier(value, label) {
    var normalized = trimText(value);
    if (!/^[A-Za-z0-9][A-Za-z0-9:._-]{0,127}$/.test(normalized)) {
      throw new Error(label + " 식별자 설정을 확인해 주세요.");
    }
    return normalized;
  }

  function signingSecret() {
    var secret = readPrivateSetting(SETTING_SIGNING_SECRET);
    if (utf8(secret).length < 32) {
      throw new Error("V2 서명 키가 없거나 너무 짧습니다. 봇의 비공개 설정을 확인해 주세요.");
    }
    return secret;
  }

  function identitySecret() {
    var secret = readPrivateSetting(SETTING_IDENTITY_SECRET);
    if (utf8(secret).length < 32) {
      throw new Error("V2 익명 식별 키가 없거나 너무 짧습니다. 봇의 비공개 설정을 확인해 주세요.");
    }
    return secret;
  }

  function randomNonce() {
    return String(java.util.UUID.randomUUID().toString()).replace(/-/g, "");
  }

  function newUuid() {
    return String(java.util.UUID.randomUUID().toString());
  }

  function idempotencyKey(nonce) {
    return "mbr-v41-" + nonce;
  }

  function signatureMaterial(timestampSeconds, nonce, roomId, senderId, bodyDigestHex) {
    return [CONTRACT_VERSION, timestampSeconds, nonce, roomId, senderId, bodyDigestHex].join("\n");
  }

  function safeJsonParse(value) {
    try {
      return JSON.parse(String(value || ""));
    } catch (ignored) {
      return null;
    }
  }

  function request(path, payload, context) {
    if (!context || typeof context !== "object") throw new Error("V2 요청 컨텍스트가 필요합니다.");
    if (!Object.prototype.hasOwnProperty.call(ENDPOINTS, context.endpointName) || ENDPOINTS[context.endpointName] !== path) {
      throw new Error("허용되지 않은 V2 API 경로입니다.");
    }
    var rawBody = JSON.stringify(payload);
    var roomId = safeIdentifier(context.roomId, "방");
    var senderId = safeIdentifier(context.senderId, "발신자");
    var nonce = randomNonce();
    var timestampSeconds = Math.floor(new Date().getTime() / 1000);
    var bodyDigestHex = sha256Hex(rawBody);
    var signature = "v1=" + hmacSha256Hex(
      signingSecret(),
      signatureMaterial(timestampSeconds, nonce, roomId, senderId, bodyDigestHex)
    );
    var connection = org.jsoup.Jsoup.connect(normalizeBaseUrl(readPrivateSetting(SETTING_BASE_URL)) + path)
      .ignoreContentType(true)
      .ignoreHttpErrors(true)
      .method(org.jsoup.Connection.Method.POST)
      .header("Content-Type", "application/json; charset=utf-8")
      .header("Accept", "application/json")
      .header("x-klol-timestamp", String(timestampSeconds))
      .header("x-klol-nonce", nonce)
      .header("x-klol-room", roomId)
      .header("x-klol-sender", senderId)
      .header("x-klol-bot-self", context.botSelf === true ? "1" : "0")
      .header("x-klol-signature", signature)
      .header("Idempotency-Key", context.requestKey || idempotencyKey(nonce))
      .timeout(typeof context.timeoutMs === "number" ? Math.floor(context.timeoutMs) : 12000)
      .requestBody(rawBody);
    if (path === ENDPOINTS.imageReceive) connection.maxBodySize(0);
    if (typeof context.expectedRevision === "number" && context.expectedRevision >= 0) {
      connection.header("If-Match", "\"" + String(Math.floor(context.expectedRevision)) + "\"");
    }
    var response = connection.execute();
    var parsed = safeJsonParse(response.body());
    return {
      ok: response.statusCode() >= 200 && response.statusCode() < 300,
      status: response.statusCode(),
      body: parsed,
      traceId: trimText(response.header("X-Trace-Id"))
    };
  }

  function contextFor(endpointName, context) {
    var next = {};
    var key = "";
    context = context || {};
    for (key in context) {
      if (Object.prototype.hasOwnProperty.call(context, key)) next[key] = context[key];
    }
    next.endpointName = endpointName;
    return next;
  }

  function identityForChat(room, sender) {
    var secret = identitySecret();
    return {
      roomId: "room-" + hmacSha256Hex(secret, "room-id\n" + trimText(room)).substring(0, 32),
      senderId: "sender-" + hmacSha256Hex(secret, "sender-id\n" + trimText(sender)).substring(0, 32)
    };
  }

  function contextFromChat(room, sender, options) {
    var identity = identityForChat(room, sender);
    var context = { roomId: identity.roomId, senderId: identity.senderId, botSelf: false };
    var key = "";
    options = options || {};
    for (key in options) {
      if (Object.prototype.hasOwnProperty.call(options, key)) context[key] = options[key];
    }
    return context;
  }

  function recruit(command, context) {
    if (!context || typeof context.expectedRevision !== "number") {
      throw new Error("모집 요청에는 최신 revision이 필요합니다.");
    }
    return request(ENDPOINTS.recruit, command, contextFor("recruit", context));
  }

  function searchPlayer(query, context) {
    return request(ENDPOINTS.playerSearch, { query: String(query || "") }, contextFor("playerSearch", context));
  }

  function openchatStatus(context) {
    return request(ENDPOINTS.openchat, { command: "STATUS" }, contextFor("openchat", context));
  }

  function openchatSearch(query, context) {
    return request(ENDPOINTS.openchat, { command: "SEARCH_PLAYER", query: String(query || "") }, contextFor("openchat", context));
  }

  function seasonApplications(command, context) {
    return request(ENDPOINTS.seasonApplications, command, contextFor("seasonApplications", context));
  }

  function managedForm(formType, payload, context) {
    return request(ENDPOINTS.managedForms, {
      command: "SUBMIT_OPERATION_FORM",
      formType: formType,
      payload: payload
    }, contextFor("managedForms", context));
  }

  function operationForm(formType, payload, context) {
    return request(ENDPOINTS.operationForms, { formType: formType, payload: payload }, contextFor("operationForms", context));
  }

  function imageReceive(command, context) {
    return request(ENDPOINTS.imageReceive, command, contextFor("imageReceive", context));
  }

  function scheduledNotice(slot, context) {
    return request(ENDPOINTS.scheduledNotice, slot == null ? {} : { slot: slot }, contextFor("scheduledNotice", context));
  }

  function userMessage(result) {
    if (result && result.ok) return "[K-LOL.GG]\n요청을 안전하게 처리했습니다.";
    var body = result && result.body && typeof result.body === "object" ? result.body : null;
    var detail = body && typeof body.detail === "string" ? body.detail : "잠시 후 다시 시도해 주세요.";
    var trace = result && result.traceId ? "\n문의 코드: " + result.traceId : "";
    return "[K-LOL.GG 요청 실패]\n" + detail + trace;
  }

  return {
    version: "KLOL_KAKAO_BOT_V41_V2_TRANSPORT_2026_09_08",
    contractVersion: CONTRACT_VERSION,
    identityForChat: identityForChat,
    contextFromChat: contextFromChat,
    sha256Base64BytesHex: sha256Base64BytesHex,
    newUuid: newUuid,
    recruit: recruit,
    searchPlayer: searchPlayer,
    openchatStatus: openchatStatus,
    openchatSearch: openchatSearch,
    seasonApplications: seasonApplications,
    managedForm: managedForm,
    operationForm: operationForm,
    imageReceive: imageReceive,
    scheduledNotice: scheduledNotice,
    userMessage: userMessage
  };
}());

/* eslint-disable */
/*
 * K-LOL.GG MessengerBot R V41 command router.
 * Build the paste-ready single file with scripts/build-messengerbot-v41.mjs.
 * This router requires KLOL_KAKAO_BOT_V41_V2_TRANSPORT.js immediately before it.
 */
var KLOL_V41_BOT_CODE_VERSION = "KLOL_KAKAO_BOT_V41_V2_2026_09_08";
var KLOL_V41_SITE_URL = "https://k-lol-gg.vercel.app";

function v41Trim(value) {
  return String(value == null ? "" : value).replace(/^\s+|\s+$/g, "");
}

function v41PrivateSetting(key) {
  try {
    return v41Trim(String(DataBase.getDataBase(key) || ""));
  } catch (ignored) {
    return "";
  }
}

function v41Reply(replier, text) {
  if (replier && replier.reply) replier.reply(String(text));
}

function v41ResultMessage(result) {
  return KLOL_V2_KAKAO.userMessage(result);
}

function v41Today() {
  var formatter = new java.text.SimpleDateFormat("yyyy-MM-dd");
  formatter.setTimeZone(java.util.TimeZone.getTimeZone("Asia/Seoul"));
  return String(formatter.format(new java.util.Date()));
}

function v41RecruitNumber(text) {
  var match = String(text || "").match(/#\s*(\d{1,3})/);
  var value = match ? Number(match[1]) : 1;
  return value >= 1 && value <= 999 ? value : 1;
}

function v41SeasonId() {
  var value = v41PrivateSetting("KLOL_V2_ACTIVE_SEASON_ID");
  if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)) {
    throw new Error("V2 활성 시즌 ID 설정을 확인해 주세요.");
  }
  return value;
}

function v41FormatSearch(result) {
  var body = result && result.body;
  var items = body && body.items instanceof Array ? body.items : [];
  var lines = ["[K-LOL.GG 전적 검색]"];
  var index = 0;
  if (!result || !result.ok) return v41ResultMessage(result);
  if (!items.length) return lines[0] + "\n검색 결과가 없습니다.";
  for (index = 0; index < items.length; index += 1) {
    lines.push((index + 1) + ". " + items[index].displayName + " · " + items[index].riotId +
      (items[index].tier ? " · " + items[index].tier : ""));
  }
  if (body.truncated) lines.push("일부 결과만 표시했습니다.");
  return lines.join("\n");
}

function v41FormatOpenchat(result) {
  var body = result && result.body;
  var parties = body && body.parties instanceof Array ? body.parties : [];
  var scrims = body && body.scrims instanceof Array ? body.scrims : [];
  var lines = ["[K-LOL.GG 구인 현황]"];
  var index = 0;
  if (!result || !result.ok) return v41ResultMessage(result);
  for (index = 0; index < parties.length; index += 1) {
    lines.push("파티 #" + parties[index].recruitNumber + " · " + parties[index].title + " · " +
      parties[index].memberCount + "/" + parties[index].maximumMembers);
  }
  for (index = 0; index < scrims.length; index += 1) {
    lines.push("스크림 #" + scrims[index].scrimNumber + " · " + scrims[index].status + " · BO" + scrims[index].bestOf);
  }
  if (lines.length === 1) lines.push("현재 진행 중인 모집이 없습니다.");
  return lines.join("\n");
}

function v41FormatSeason(result) {
  var body = result && result.body;
  var entries = body && body.entries instanceof Array ? body.entries : [];
  var lines = ["[K-LOL.GG 내전 현황]"];
  var index = 0;
  if (!result || !result.ok) return v41ResultMessage(result);
  lines.push("신청 " + body.appliedCount + " · 예비 " + body.reserveCount + " · 확인 필요 " + body.pendingCount);
  for (index = 0; index < entries.length; index += 1) {
    lines.push(entries[index].slotNo + ". " + entries[index].suppliedName + " · " + entries[index].status);
  }
  return lines.join("\n");
}

function v41Position(value) {
  var token = v41Trim(value).toUpperCase();
  if (token === "탑" || token === "T") return "TOP";
  if (token === "정글" || token === "JG" || token === "JUG") return "JGL";
  if (token === "미드" || token === "MD" || token === "M") return "MID";
  if (token === "원딜" || token === "AD" || token === "원딜러") return "ADC";
  if (token === "서폿" || token === "서포터" || token === "S") return "SUP";
  if (token === "올" || token === "전체" || token === "FILL") return "ALL";
  if (/^(TOP|JGL|MID|ADC|SUP|ALL)$/.test(token)) return token;
  return null;
}

function v41SeasonParticipants(text) {
  var lines = String(text || "").replace(/\r\n?/g, "\n").split("\n");
  var participants = [];
  var index = 0;
  for (index = 0; index < lines.length; index += 1) {
    var match = v41Trim(lines[index]).match(/^(\d{1,2})\s*[.)]\s*(.+)$/);
    if (!match || match[2].indexOf("/") < 0 || /^(?:EX|예시)/i.test(match[2])) continue;
    var fields = match[2].split("/");
    if (fields.length < 4) continue;
    var name = v41Trim(fields[0]);
    var positions = v41Trim(fields.slice(3).join("/")).split(/[,，]/);
    var main = v41Position(positions[0]);
    if (!name || !main) throw new Error(match[1] + "번 신청자의 이름 또는 포지션을 확인해 주세요.");
    var subs = [];
    var subIndex = 1;
    for (subIndex = 1; subIndex < positions.length; subIndex += 1) {
      var sub = v41Position(positions[subIndex]);
      if (sub && sub !== main && sub !== "ALL" && subs.indexOf(sub) < 0) subs.push(sub);
    }
    participants.push({
      slotNo: Number(match[1]), name: name, riotId: null, mainPosition: main,
      subPositions: subs, reserve: /(?:예비|대기)/.test(match[2])
    });
  }
  if (!participants.length) throw new Error("내전 신청자 줄을 찾지 못했습니다.");
  return participants;
}

function v41DateFromSnapshot(text) {
  var match = String(text || "").match(/(20\d{2}-\d{2}-\d{2})/);
  return match ? match[1] : v41Today();
}

function v41JsonAfter(text, prefix) {
  var parsed = JSON.parse(v41Trim(String(text).substring(prefix.length)));
  if (!parsed || typeof parsed !== "object" || parsed instanceof Array) throw new Error("JSON 객체 형식을 확인해 주세요.");
  return parsed;
}

function v41RecruitKind(type) {
  return String(type || "").indexOf("SCRIM") >= 0 ? "SCRIM" : "PARTY";
}

function v41RecruitStateKey(room, kind) {
  var identity = KLOL_V2_KAKAO.identityForChat(room, "recruit-state");
  return "KLOL_V41_RECRUIT_" + kind + "_" + identity.roomId.substring(5);
}

function v41ReadRecruitState(room, kind) {
  try {
    var value = JSON.parse(String(DataBase.getDataBase(v41RecruitStateKey(room, kind)) || "null"));
    if (value && typeof value.aggregateId === "string" && typeof value.revision === "number") return value;
  } catch (ignored) {}
  return null;
}

function v41SaveRecruitState(room, kind, result) {
  var body = result && result.body;
  if (!result || !result.ok || !body || typeof body.aggregateId !== "string" || typeof body.revision !== "number") return;
  DataBase.setDataBase(v41RecruitStateKey(room, kind), JSON.stringify({
    aggregateId: body.aggregateId, revision: body.revision, status: body.status
  }));
}

function v41HandleRecruitJson(text, room, sender, replier) {
  var input = v41JsonAfter(text, "/V2모집");
  var type = String(input.type || "");
  var kind = v41RecruitKind(type);
  var create = type.indexOf("CREATE_") === 0;
  var saved = create ? null : v41ReadRecruitState(room, kind);
  var aggregateId = typeof input.aggregateId === "string" ? input.aggregateId : (saved ? saved.aggregateId : "");
  var expectedRevision = typeof input.expectedRevision === "number" ? input.expectedRevision : (create ? 0 : (saved ? saved.revision : -1));
  if (create && !aggregateId) aggregateId = KLOL_V2_KAKAO.newUuid();
  if (!aggregateId || expectedRevision < 0) throw new Error("모집 ID 또는 최신 revision을 확인해 주세요.");
  var payload = { type: type, aggregateId: aggregateId, payload: input.payload };
  var result = KLOL_V2_KAKAO.recruit(payload, KLOL_V2_KAKAO.contextFromChat(room, sender, {
    expectedRevision: expectedRevision
  }));
  v41SaveRecruitState(room, kind, result);
  v41Reply(replier, v41ResultMessage(result));
}

function v41ImageSaveKey(room, sender) {
  var identity = KLOL_V2_KAKAO.identityForChat(room, sender);
  return "KLOL_V41_IMAGE_SESSION_" + identity.roomId.substring(5) + "_" + identity.senderId.substring(7);
}

function v41SaveImageSession(room, sender, sessionId) {
  if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(sessionId)) {
    throw new Error("사진 세션 ID를 확인해 주세요.");
  }
  DataBase.setDataBase(v41ImageSaveKey(room, sender), sessionId + "|" + String(new Date().getTime()));
}

function v41ReadImageSession(room, sender) {
  var saved = String(DataBase.getDataBase(v41ImageSaveKey(room, sender)) || "").split("|");
  var savedAt = Number(saved[1] || 0);
  if (!savedAt || new Date().getTime() - savedAt > 30 * 60 * 1000) return "";
  return v41Trim(saved[0]);
}

function v41ReceivedImage(imageDB) {
  var value = "";
  try { if (imageDB && imageDB.getImageBase64) value = String(imageDB.getImageBase64() || ""); } catch (ignored) {}
  try { if (!value && imageDB && imageDB.getImage) value = String(imageDB.getImage() || ""); } catch (ignored2) {}
  return value;
}

function v41HandleImage(room, sender, rawImage, replier) {
  var sessionId = v41ReadImageSession(room, sender);
  if (!sessionId) return false;
  var contentType = "image/jpeg";
  var match = String(rawImage).match(/^data:(image\/(?:png|jpeg|webp));base64,(.+)$/i);
  var base64Image = match ? match[2] : String(rawImage);
  if (match) contentType = match[1].toLowerCase();
  base64Image = base64Image.replace(/\s+/g, "");
  var result = KLOL_V2_KAKAO.imageReceive({
    sessionId: sessionId,
    base64Image: base64Image,
    declaredContentType: contentType,
    declaredSha256Hex: KLOL_V2_KAKAO.sha256Base64BytesHex(base64Image),
    originalFileName: null
  }, KLOL_V2_KAKAO.contextFromChat(room, sender, { timeoutMs: 90000 }));
  v41Reply(replier, v41ResultMessage(result));
  return true;
}

function v41Help() {
  return [
    "[K-LOL.GG V41 도움말]",
    "전적 닉네임#태그 · 구인현황 · 내전현황",
    "내전 신청 양식 전체 전송(SYNC)",
    "/V2연동확인 · /V2사진세션 <사이트 발급 UUID>",
    "운영자 구조화 명령: /V2모집, /V2시즌, /V2양식 뒤에 JSON 객체",
    "구형 free-text 파티/스크림 등록은 안전을 위해 사이트에서 진행: " + KLOL_V41_SITE_URL + "/recruit"
  ].join("\n");
}

function response(room, msg, sender, isGroupChat, replier, imageDB, packageName) {
  var text = v41Trim(String(msg || "").replace(/\r\n?/g, "\n"));
  var rawImage = v41ReceivedImage(imageDB);
  try {
    if (rawImage && v41HandleImage(room, sender, rawImage, replier)) return;
    if (text === "/봇버전" || text === "봇버전") return v41Reply(replier, "[K-LOL.GG 카카오봇]\n" + KLOL_V41_BOT_CODE_VERSION);
    if (text === "/도움말" || text === "도움말" || text === "/명령어" || text === "명령어") return v41Reply(replier, v41Help());
    if (text === "/V2연동확인") {
      var identity = KLOL_V2_KAKAO.identityForChat(room, sender);
      return v41Reply(replier, "[K-LOL.GG V2 연동 ID]\n방: " + identity.roomId + "\n발신자: " + identity.senderId);
    }
    if (/^\/?전적\s+/.test(text)) {
      return v41Reply(replier, v41FormatSearch(KLOL_V2_KAKAO.searchPlayer(text.replace(/^\/?전적\s+/, ""), KLOL_V2_KAKAO.contextFromChat(room, sender))));
    }
    if (/^\/?(?:구인현황|스크림현황)$/.test(text)) {
      return v41Reply(replier, v41FormatOpenchat(KLOL_V2_KAKAO.openchatStatus(KLOL_V2_KAKAO.contextFromChat(room, sender))));
    }
    if (/^\/?내전현황(?:\s*#?\d{1,3})?$/.test(text)) {
      return v41Reply(replier, v41FormatSeason(KLOL_V2_KAKAO.seasonApplications({
        action: "STATUS", seasonId: v41SeasonId(), applyDate: v41Today(), recruitNo: v41RecruitNumber(text)
      }, KLOL_V2_KAKAO.contextFromChat(room, sender))));
    }
    if (/협곡\s*내전|참가\s*신청\s*양식/.test(text) && /^\s*\d{1,2}\s*[.)]/m.test(text)) {
      return v41Reply(replier, v41FormatSeason(KLOL_V2_KAKAO.seasonApplications({
        action: "SYNC", seasonId: v41SeasonId(), applyDate: v41DateFromSnapshot(text),
        recruitNo: v41RecruitNumber(text), participants: v41SeasonParticipants(text)
      }, KLOL_V2_KAKAO.contextFromChat(room, sender))));
    }
    if (text.indexOf("/V2모집 ") === 0) return v41HandleRecruitJson(text, room, sender, replier);
    if (text.indexOf("/V2시즌 ") === 0) {
      return v41Reply(replier, v41FormatSeason(KLOL_V2_KAKAO.seasonApplications(v41JsonAfter(text, "/V2시즌"), KLOL_V2_KAKAO.contextFromChat(room, sender))));
    }
    if (text.indexOf("/V2양식 ") === 0) {
      var form = v41JsonAfter(text, "/V2양식");
      return v41Reply(replier, v41ResultMessage(KLOL_V2_KAKAO.operationForm(form.formType, form.payload, KLOL_V2_KAKAO.contextFromChat(room, sender))));
    }
    if (text.indexOf("/V2사진세션 ") === 0) {
      v41SaveImageSession(room, sender, v41Trim(text.substring("/V2사진세션".length)));
      return v41Reply(replier, "[K-LOL.GG 사진 접수]\n30분 동안 이 대화의 다음 사진을 안전하게 접수합니다.");
    }
    if (/^\/?(?:5인파티|구인생성|구인마감|스크림구인|스크림모집)/.test(text)) {
      return v41Reply(replier, "[K-LOL.GG 안전 전환 안내]\n구형 문장형 등록은 종료되었습니다. 사이트 또는 /V2모집 구조화 명령을 이용해 주세요.\n" + KLOL_V41_SITE_URL + "/recruit");
    }
  } catch (error) {
    v41Reply(replier, "[K-LOL.GG 요청 실패]\n설정 또는 입력 형식을 확인해 주세요.");
  }
}

response.__kakaoBotEntryPoint = true;
