export type NavigationMode = "user" | "admin";

export type NavigationItem = {
  href: string;
  appHref?: string;
  label: string;
  description: string;
  section: string;
  keywords: string[];
  access?: "SUPER";
};

const userNavigation: NavigationItem[] = [
  {
    href: "/start",
    appHref: "/start",
    label: "등록·제출 시작",
    description: "내전 결과·경고 사진·관리자 등록을 안내에 따라 시작",
    section: "바로가기",
    keywords: ["등록", "제출", "처음", "시작", "내전 결과", "경고", "인증", "사진"],
  },
  {
    href: "/",
    appHref: "/app",
    label: "홈",
    description: "최근 경기와 시즌 현황",
    section: "바로가기",
    keywords: ["메인", "대시보드"],
  },
  {
    href: "/recruit",
    appHref: "/app/recruits",
    label: "구인 현황",
    description: "현재 모집 중인 파티 확인",
    section: "바로가기",
    keywords: ["구인", "파티", "모집", "스크림"],
  },
  {
    href: "/matches",
    appHref: "/app/matches",
    label: "내전 목록",
    description: "최근 내전 결과와 상세 기록",
    section: "경기",
    keywords: ["내전", "경기", "전적", "최근 전적", "결과"],
  },
  {
    href: "/matches/submit",
    appHref: "/matches/submit",
    label: "내전 결과 제출",
    description: "진행 정보와 결과 사진을 한 번에 제출",
    section: "경기",
    keywords: ["내전", "결과", "사진", "제출", "등록", "접수번호"],
  },
  {
    href: "/discipline/evidence",
    appHref: "/discipline/evidence",
    label: "경고 차감 사진 제출",
    description: "남은 인증 사진을 한 번에 제출",
    section: "내 계정",
    keywords: ["경고", "차감", "인증", "사진", "제출", "WR"],
  },
  {
    href: "/rankings",
    appHref: "/app/rankings",
    label: "시즌 랭킹",
    description: "승률·MVP·참여 순위",
    section: "경기",
    keywords: ["랭킹", "순위", "시즌", "mvp", "수상", "승률"],
  },
  {
    href: "/players",
    appHref: "/app/players",
    label: "플레이어 검색",
    description: "플레이어 프로필과 전적 검색",
    section: "플레이어",
    keywords: ["회원", "검색", "프로필", "개인 전적", "챔피언별 전적", "kda"],
  },
  {
    href: "/ai-balance",
    appHref: "/app/rankings",
    label: "K-LOL MMR",
    description: "밸런스 점수와 지표 확인",
    section: "플레이어",
    keywords: ["mmr", "점수", "밸런스"],
  },
  {
    href: "/players/balance",
    appHref: "/players/balance",
    label: "팀 밸런스",
    description: "참가자를 두 팀으로 배정",
    section: "도구",
    keywords: ["팀", "나누기", "밸런스"],
  },
  {
    href: "/players/balance/recommendations",
    appHref: "/players/balance/recommendations",
    label: "밴픽·조합 추천",
    description: "팀 조합과 밴픽 추천 확인",
    section: "도구",
    keywords: ["밴픽", "챔피언", "조합", "추천", "듀오 시너지"],
  },
  {
    href: "/random-team",
    appHref: "/app/random-team",
    label: "랜덤 팀 나누기",
    description: "빠르게 무작위 팀 생성",
    section: "도구",
    keywords: ["랜덤", "팀", "추첨"],
  },
  {
    href: "/progress",
    appHref: "/app/matches?tab=events",
    label: "이벤트·멸망전",
    description: "대회 진행 현황과 결과",
    section: "대회",
    keywords: ["이벤트", "멸망전", "대회", "스크림", "일정", "캘린더", "대진표"],
  },
  {
    href: "/participation",
    appHref: "/participation",
    label: "참여할 이벤트 찾기",
    description: "모집 중·예정·진행 중인 이벤트와 내 신청 확인",
    section: "대회",
    keywords: ["참가", "신청", "접수", "내 일정", "대기", "승인", "알림"],
  },
  {
    href: "/coin-toss",
    appHref: "/app/coin-toss",
    label: "코인토스",
    description: "진영과 순서를 공정하게 추첨",
    section: "도구",
    keywords: ["코인", "추첨", "진영"],
  },
  {
    href: "/highlights",
    appHref: "/highlights",
    label: "하이라이트",
    description: "경기 영상과 주요 장면",
    section: "콘텐츠",
    keywords: ["영상", "클립", "이미지"],
  },
  {
    href: "/images",
    appHref: "/images",
    label: "사진 갤러리",
    description: "내전과 이벤트 사진 모아보기",
    section: "콘텐츠",
    keywords: ["사진", "이미지", "갤러리"],
  },
  {
    href: "/me/riot",
    appHref: "/app/me/riot",
    label: "Riot 계정·티어",
    description: "Riot 계정 연결과 티어 동기화",
    section: "내 계정",
    keywords: ["라이엇", "riot", "롤", "티어", "계정 연동"],
  },
  {
    href: "/account",
    appHref: "/app/me",
    label: "내 정보",
    description: "계정과 연결된 플레이어 관리",
    section: "내 계정",
    keywords: ["계정", "프로필", "티어"],
  },
  {
    href: "/install",
    appHref: "/app/install",
    label: "앱 설치",
    description: "K-LOL.GG 모바일 앱 설치 안내",
    section: "내 계정",
    keywords: ["앱", "apk", "설치", "모바일"],
  },
  {
    href: "/kakao",
    appHref: "/kakao",
    label: "카카오톡 봇 안내",
    description: "카카오톡 명령어와 연동 기능",
    section: "도움말",
    keywords: ["카카오", "카톡", "봇", "명령어", "자동화"],
  },
  {
    href: "/recruit-helper",
    appHref: "/recruit-helper",
    label: "구인 도우미",
    description: "구인 명령과 사용 방법 확인",
    section: "도움말",
    keywords: ["구인", "도움말", "사용법", "파티"],
  },
];

const adminNavigation: NavigationItem[] = [
  {
    href: "/start",
    appHref: "/start",
    label: "등록·제출 허브",
    description: "내전 결과·경고 등록 흐름을 한 화면에서 시작",
    section: "오늘 운영",
    keywords: ["등록", "제출", "내전", "경고", "허브", "시작"],
  },
  {
    href: "/admin",
    appHref: "/app/admin",
    label: "관리자 홈",
    description: "오늘 운영 현황과 주요 알림",
    section: "오늘 운영",
    keywords: ["대시보드", "메인"],
  },
  {
    href: "/admin/matches/new",
    appHref: "/app/admin/matches",
    label: "새 내전 등록",
    description: "경기 참가자와 결과 입력",
    section: "오늘 운영",
    keywords: ["내전", "등록", "경기"],
  },
  {
    href: "/admin/matches/submissions",
    appHref: "/admin/matches/submissions",
    label: "내전 결과 접수",
    description: "제출된 결과 사진과 등록 상태 확인",
    section: "오늘 운영",
    keywords: ["내전", "결과", "사진", "접수", "검토"],
  },
  {
    href: "/admin/matches",
    appHref: "/app/admin/matches",
    label: "내전 관리",
    description: "등록된 내전 조회와 수정",
    section: "오늘 운영",
    keywords: ["내전", "경기", "결과"],
  },
  {
    href: "/admin/kakao/recruits",
    appHref: "/app/admin/recruits",
    label: "구인 관리",
    description: "진행 중인 구인과 참가자 확인",
    section: "오늘 운영",
    keywords: ["구인", "파티", "모집"],
  },
  {
    href: "/admin/kakao/scrims",
    appHref: "/admin/kakao/scrims",
    label: "스크림 구인",
    description: "스크림 모집과 일정 현황 관리",
    section: "오늘 운영",
    keywords: ["스크림", "팀", "일정", "캘린더", "모집"],
  },
  {
    href: "/admin/progress",
    appHref: "/admin/progress",
    label: "이벤트·멸망전 관리",
    description: "대회 생성과 진행 관리",
    section: "오늘 운영",
    keywords: ["이벤트", "멸망전", "대회"],
  },
  {
    href: "/admin/kakao/season-apply",
    appHref: "/admin/kakao/season-apply",
    label: "참가 신청 확인",
    description: "내전 참가 신청과 대기자 처리",
    section: "오늘 운영",
    keywords: ["참가", "신청", "대기"],
  },
  {
    href: "/admin/progress/event/new",
    appHref: "/admin/progress/event/new",
    label: "새 이벤트 만들기",
    description: "이벤트 일정과 참가 설정 생성",
    section: "오늘 운영",
    keywords: ["이벤트", "신규", "생성", "일정"],
  },
  {
    href: "/admin/progress/destruction/new",
    appHref: "/admin/progress/destruction/new",
    label: "새 멸망전 만들기",
    description: "멸망전 일정과 진행 단계 생성",
    section: "오늘 운영",
    keywords: ["멸망전", "신규", "생성", "대진표"],
  },
  {
    href: "/admin/players",
    appHref: "/admin/players",
    label: "플레이어 관리",
    description: "플레이어 정보 조회와 수정",
    section: "사람 관리",
    keywords: ["플레이어", "회원", "검색"],
  },
  {
    href: "/admin/players/new",
    appHref: "/app/admin/users",
    label: "새 플레이어 등록",
    description: "플레이어 기본 정보 직접 등록",
    section: "사람 관리",
    keywords: ["플레이어", "회원", "신규", "등록"],
  },
  {
    href: "/admin/users",
    appHref: "/app/admin/users",
    label: "계정 관리",
    description: "가입 계정과 권한 확인",
    section: "사람 관리",
    keywords: ["계정", "회원", "권한"],
  },
  {
    href: "/admin/discipline",
    appHref: "/admin/discipline",
    label: "주의·경고·벤",
    description: "징계 기록 등록과 조회",
    section: "사람 관리",
    keywords: ["징계", "경고", "벤"],
  },
  {
    href: "/admin/discipline/new",
    appHref: "/admin/discipline/new",
    label: "징계 바로 등록",
    description: "주의·경고·벤 기록 추가",
    section: "사람 관리",
    keywords: ["징계", "주의", "경고", "벤", "등록"],
  },
  {
    href: "/admin/kakao/operation-forms",
    appHref: "/admin/kakao/operation-forms",
    label: "운영 신청",
    description: "운영 관련 신청 내역 확인",
    section: "사람 관리",
    keywords: ["운영", "신청", "접수"],
  },
  {
    href: "/admin/logs/kakao",
    appHref: "/admin/logs/kakao",
    label: "카카오톡 처리 로그",
    description: "자동화 처리와 오류 기록",
    section: "자동화",
    keywords: ["카카오", "로그", "오류"],
  },
  {
    href: "/admin/kakao",
    appHref: "/admin/kakao",
    label: "카카오톡 운영 요약",
    description: "카카오 자동화와 운영 현황 확인",
    section: "자동화",
    keywords: ["카카오", "카톡", "봇", "자동화", "요약"],
  },
  {
    href: "/admin/riot",
    appHref: "/admin/riot",
    label: "Riot 연동 관리",
    description: "Riot 계정 연결과 동기화 상태",
    section: "자동화",
    keywords: ["riot", "라이엇", "티어", "동기화", "연동"],
  },
  {
    href: "/admin/balance-ai",
    appHref: "/admin/balance-ai",
    label: "K-LOL MMR 관리",
    description: "MMR 지표와 AI 평가 관리",
    section: "자동화",
    keywords: ["mmr", "밸런스", "ai", "평가", "승률 예측"],
  },
  {
    href: "/admin/ai-requests",
    appHref: "/admin/ai-requests",
    label: "AI 요청 로그",
    description: "AI 사용 기록과 오류 확인",
    section: "자동화",
    keywords: ["ai", "로그", "요청", "오류"],
    access: "SUPER",
  },
  {
    href: "/admin/balance/drafts",
    appHref: "/admin/balance/drafts",
    label: "AI 팀 밸런스",
    description: "팀 배정안과 추천 결과 관리",
    section: "콘텐츠·데이터",
    keywords: ["팀", "밸런스", "라인", "포지션", "추천", "밴픽"],
  },
  {
    href: "/admin/highlights",
    appHref: "/admin/highlights",
    label: "하이라이트 관리",
    description: "경기 영상과 주요 장면 등록",
    section: "콘텐츠·데이터",
    keywords: ["영상", "하이라이트", "클립", "등록"],
  },
  {
    href: "/admin/images",
    appHref: "/admin/images",
    label: "이미지 관리",
    description: "갤러리와 홈 이미지 관리",
    section: "콘텐츠·데이터",
    keywords: ["사진", "이미지", "갤러리", "홈"],
  },
  {
    href: "/admin/site-settings",
    appHref: "/admin/site-settings",
    label: "사이트 설정",
    description: "브랜드와 기능 공개 범위 설정",
    section: "설정",
    keywords: ["사이트", "기능", "설정"],
    access: "SUPER",
  },
  {
    href: "/admin/kakao/settings",
    appHref: "/admin/kakao/settings",
    label: "자동화 설정",
    description: "카카오톡 명령과 동작 설정",
    section: "설정",
    keywords: ["카카오", "자동화", "설정"],
  },
  {
    href: "/admin/security",
    appHref: "/admin/security",
    label: "보안 설정",
    description: "관리자 접근과 인증 점검",
    section: "설정",
    keywords: ["보안", "인증", "관리자"],
  },
  {
    href: "/admin/seasons",
    appHref: "/admin/seasons",
    label: "시즌 관리",
    description: "시즌 생성·활성화·종료 관리",
    section: "설정",
    keywords: ["시즌", "랭킹", "시작", "종료"],
  },
  {
    href: "/admin/champions",
    appHref: "/admin/champions",
    label: "챔피언 관리",
    description: "챔피언 데이터와 이미지 관리",
    section: "설정",
    keywords: ["챔피언", "롤", "이미지", "데이터"],
  },
  {
    href: "/admin/logs",
    appHref: "/admin/logs",
    label: "감사 로그",
    description: "관리자 변경·오류 이력 확인",
    section: "설정",
    keywords: ["감사", "관리자", "로그", "변경", "오류"],
    access: "SUPER",
  },
];

export function getNavigationCatalog(mode: NavigationMode) {
  return mode === "admin" ? adminNavigation : userNavigation;
}

export function getNavigationHref(item: NavigationItem, surface: "web" | "app") {
  return surface === "app" ? item.appHref ?? item.href : item.href;
}
